import React, { createContext, useContext, useState, useEffect } from 'react';

const LS_KEY = 'app_language';

const translations = {
  en: {
    // Home
    tagline: 'The Interactive Guessing Game',
    guessLaughWin: 'Guess. Laugh. Win.',
    subtitle: "Guess what the other player(s) picked, be the fastest and win!",
    players: '2–12 players',
    guessing: 'Guessing',
    realtime: 'Real-time',
    whatsYourName: "What's your name?",
    displayNamePlaceholder: 'Your display name',
    letsPlay: "Let's Play!",
    playingAs: 'Playing as',
    online: 'Online',
    change: 'Change',
    createGame: 'Create Game',
    createGameDesc: 'Be the host and challenge your friends!',
    creating: 'Creating...',
    host: 'HOST',
    join: 'JOIN',
    browse: 'BROWSE',
    gameVisibility: 'GAME VISIBILITY',
    publicLobby: 'Public',
    publicLobbyDesc: 'Anyone can join',
    privateLobby: 'Private',
    privateLobbyDesc: 'Join by room code',
    joinGame: 'Join Game',
    joinGameDesc: 'Enter a room code to join the fun.',
    roomCodePlaceholder: 'Code',
    openLobbies: 'Browse Games',
    openLobbiesDesc: 'Join an open game and play now.',
    loading: 'Loading…',
    noOpenLobbies: 'No open lobbies right now. Create one!',
    waiting: 'waiting',
    howToPlay: 'How to Play 🎉',
    howToPlayShort: 'How to play',
    settings: 'Settings',
    gotIt: 'Got it!',
    howToPlaySteps: [
      { title: 'Create a Public or Private Lobby.', body: 'Invite your friends or let others join your public game.' },
      { title: 'Pick a category & secret word.', body: 'The host picks a category, then everyone chooses their own secret word. Pick a word you know well enough to answer questions about. Be honest, cheating takes away the fun!' },
      { title: 'Answer the questions.', body: 'Players take turns asking Yes/No questions. Everyone answers honestly based on their own secret word.' },
      { title: 'Fill your Notebook.', body: "Every answer is automatically saved as a clue for each player. Use these clues to figure out everyone's secret word." },
      { title: 'Make a guess.', body: 'After each round of questions, every player can make one guess. A correct guess earns you 1 point.' },
      { title: 'Hint Round.', body: 'Every 5 rounds, everyone writes one short hint about their secret word to help the other players.' },
      { title: 'Win the game!', body: 'The player with the most points at the end wins! 🕵️🏆' },
    ],
    // Lobby
    waitingForPlayers: 'Waiting for players to join…',
    roomCode: 'Room Code',
    shareInvite: 'Share invite',
    shareInviteText: (code) => `Join my game on What's My Pick! Room code: ${code}`,
    linkCopied: 'Invite copied to clipboard',
    startGame: 'Start Game',
    starting: 'Starting…',
    startingIn: 'Starting in…',
    tapToCancel: 'Tap to cancel',
    needTwoPlayers: 'Need at least 2 players',
    startWith: (cat) => `Start — ${cat}`,
    leaveGame: 'Leave Game',
    waitingForHost: 'Waiting for the host to pick a category and start…',
    selectCategory: 'Select a Category',
    selectedCategory: 'Selected Category',
    changeCategory: 'Change Category',
    freeCategory: 'Free Category',
    includedWith: (pack) => `Included with ${pack}`,
    chooseCategory: 'Choose Category',
    chooseCategorySub: 'Choose one category for this game.',
    moreCategories: 'More Categories',
    unlocksLabel: 'Unlocks',
    moreCount: (n) => `+${n} more`,
    premiumBadge: 'PREMIUM',
    unlockForever: 'Unlock Forever',
    ownedBadge: 'OWNED',
    unlockAll: '🎉 Unlock Everything — $15',
    unlockAllSub: 'All packs + Custom Word Pack, forever',
    getAll: 'Get All',
    redirecting: 'Redirecting…',
    // Price comes localized from StoreKit (getPackPrices) — never hardcoded.
    unlockFor: (price) => price ? `Unlock for ${price}` : 'Unlock',
    customCategoryLabel: 'Custom words',
    customWordsUnlocked: 'Custom Words Unlocked',
    custom: 'Custom',
    // Progression
    profileTitle: 'Profile',
    collection: 'Collection',
    shop: 'Shop',
    challenges: 'Challenges',
    featured: 'Featured',
    level: 'Level',
    unlocked: 'Unlocked',
    notEnoughPicks: 'Not enough Picks yet — keep playing!',
    unlockAtLevel: 'Unlocks at level',
    statGames: 'Games',
    statWins: 'Wins',
    statWinRate: 'Win rate',
    statGuesses: 'Guesses',
    statFavorite: 'Favorite category',
    rewardsTitle: 'Match Rewards',
    levelUp: 'Level up! You reached level',
    rwComplete: 'Match completed',
    rwGuesses: 'Correct guesses',
    rwWinner: 'Match winner',
    rwPerfect: 'Perfect game',
    rwHost: 'Host bonus',
    rwStreak: 'Win streak',
    dailyChallenges: 'Daily Challenges',
    weeklyChallenges: 'Weekly Challenges',
    confirmUnlock: 'Unlock this cosmetic?',
    unlockNow: 'Unlock',
    youHave: 'You have',
    equippedNow: 'Equipped!',
    niceBtn: 'Nice!',
    rotatesDaily: 'New picks daily',
    todaysShop: "Today's Shop",
    earnByPlaying: 'Earn by Playing',
    collectionEmpty: 'Nothing here yet — check today\'s Shop or earn rewards by playing!',
    backLabel: 'Back',
    tapWordToGuess: 'Tap a word above to choose your guess',
    errorTitle: 'Something went wrong',
    enterYourName: 'Enter your name',
    enterRoomCode: 'Enter a room code',
    roomNotFound: 'Room not found',
    gameAlreadyStarted: 'Game already started',
    checkCodeTryAgain: 'Check the code and try again.',
    gameInProgressJoinNext: 'This game is in progress. You can join the next round!',
    youLeftGame: 'You left the game',
    stillGoingRejoin: 'The game is still going. Want to rejoin?',
    rejoinGame: 'Rejoin Game',
    playersCount: (n) => `${n} / 12 players`,
    lobbyFull: 'Lobby full',
    inviteHint: 'Tap to copy the room code and share it with your friends',
    enterWordFirst: 'Enter your word first',
    pickWordFirst: 'Pick a word first',
    noStatsYet: 'No profile stats yet.',
    statLevel: 'Level',
    challengeNames: {},
    roomFull: 'Room is full (max 12)',
    failedToJoin: 'Failed to join',
    failedToCreate: 'Failed to create game',
    pickCategoryFirst: 'Pick a category first',
    profileDeleted: 'Profile deleted',
    profileDeletedDesc: 'Your local profile and game data have been removed.',
    accountDeleted: 'Account deleted',
    accountDeletedDesc: 'Your account and game records have been removed.',
    deleteFailed: 'Delete failed',
    newBadge: 'NEW',
    statStreak: 'Streak',
    removeFromGame: 'Remove from game',
    removedByHost: 'The host removed you from the game',
    playerJoined: (name) => `${name} joined`,
    playerLeft: (name) => `${name} left`,
    sessionExpired: 'Your session expired — sign in again to keep syncing your account',
    collectionsLabel: 'Collections',
    collectionReward: 'Set reward',
    betaExclusive: 'Beta testers only',
    completeCollectionHint: 'Complete the collection to earn this',
    collectionComplete: 'Collection complete!',
    completionReward: 'Completion reward',
    purchaseUnavailable: 'Purchases are available in the iOS app',
    purchaseFailed: 'Purchase failed — please try again',
    purchasing: 'Purchasing…',
    restorePurchases: 'Restore Purchases',
    restorePurchasesDesc: 'Get packs you already bought back on this device.',
    restoreBtn: 'Restore',
    restoreDone: (n) => n > 0 ? `Restored ${n} pack${n > 1 ? 's' : ''}` : 'No purchases to restore',
    restoreFailed: "Couldn't restore purchases — check your connection and try again",
    supportFaq: 'Support & FAQ',
    gameInProgress: 'Game in progress',
    mutePlayer: 'Mute player',
    unmutePlayer: 'Unmute player',
    away: 'Away',
    hostLobby: (name) => `${name}'s lobby`,
    shareResult: 'Share',
    shareResultText: (won, rank, total) => won
      ? "I just won a round of What's My Pick! 🏆 Think you can outguess me?"
      : `I finished #${rank} of ${total} in What's My Pick! Think you can do better?`,
    // Share win card
    scPerfect: 'PERFECT!',
    scVictory: 'VICTORY!',
    scPlace: (rank) => `#${rank} PLACE`,
    scWordsGuessed: 'WORDS GUESSED',
    scStreakChip: (n) => `🔥 ${n} WIN STREAK`,
    shareCardCta: 'Share',
    shareCardSaved: 'Image saved',
    newStockIn: (time) => `New stock in ${time}`,
    playerFallback: 'Player',
    pageNotFound: 'Page Not Found',
    pageNotFoundBody: (page) => `The page "${page}" doesn't exist.`,
    icloudBackedUp: 'Progress backed up to iCloud',
    icloudNotBackedUp: 'Not backed up — enable iCloud for this app to protect your progress',
    reportPlayer: 'Report player',
    reportThanks: 'Reported — thank you',
    privacyPolicy: 'Privacy Policy',
    editName: 'Edit name',
    nameSaved: 'Name updated!',
    saveBtn: 'Save',
    equippedLabel: 'Equipped cosmetics',
    changeInProfile: 'Change in Profile →',
    slotLabels: { emblem: 'Emblem', border: 'Border', banner: 'Banner', title: 'Title', nameColor: 'Name style' },
    syncOk: 'Cloud sync active — other players can see your cosmetics',
    syncMissing: 'Cloud sync unavailable — other players cannot see your cosmetics. Run supabase/migrations/0002_player_profiles.sql in the Supabase SQL editor, then reload the app.',
    seasonFootnote: 'Season rewards are exclusive and never sold.',
    dailyReward: 'Daily reward',
    dayStreak: 'day streak',
    // WordEntry
    chooseSecretWord: 'Choose Your Secret Word',
    category: 'Category',
    typeAnyWord: 'Type any word for others to guess',
    enterSecretWord: 'Enter your secret word…',
    keepItSecret: "Keep it secret! Other players will try to guess it.",
    change2: 'Change',
    search: (cat) => `Search ${cat}…`,
    noResults: 'No results',
    lockIn: 'Lock In My Word',
    lockingIn: 'Locking in…',
    wordLockedIn: 'Word locked in!',
    waitingForOthers: 'Waiting for others…',
    wordTimeoutKicked: "Time's up — you didn't pick a word in time",
    wordTimeoutLobby: "Time's up — not enough players to continue, back to the lobby",
    everyoneReady: "Everyone's ready — Start!",
    you: 'YOU',
    // Playing
    myWord: 'My Word',
    hintRound: '💡 Hint Round!',
    hintRoundSub: 'After every 5 questions, everyone gives a hint about their own word. Questions resume once all hints are in.',
    hintSubmitted: '✅ Hint submitted! Waiting for others…',
    allHintsIn: '✅ All hints are in! Check everyone\'s hints in your Notebook tab.',
    giveHint: 'Give a hint about your secret word (don\'t say it directly!)',
    hintPlaceholder: 'E.g. It lives in the ocean…',
    share: 'Share',
    waitingForHints: 'Waiting for other players to submit their hints…',
    allHintsSubmitted: '💡 All hints submitted! Check them in your Notebook tab.',
    waitingForAnswers: 'Waiting for everyone to answer…',
    answerThisQuestion: 'Answer this question for YOUR word:',
    yes: '✅ Yes',
    no: '❌ No',
    yourTurnToAsk: 'Your turn to ask!',
    autoAsking: 'Auto-asking…',
    askPlaceholder: 'Ask a yes/no question…',
    askQuestion: 'Ask Question',
    skipToAI: 'Auto',
    skipTitle: 'Skip — let AI ask',
    isTurnToAsk: (name) => `${name}'s turn to ask`,
    guessIn: (n) => `Guess in ${n} ${n === 1 ? 'question' : 'questions'}`,
    guessOthers: '🎯 Your word was found, guess others!',
    makeAGuess: 'Make a Guess',
    endGame: 'End Game',
    allPlayers: 'All Players',
    wordRevealed: (word) => `Guessed! (${word})`,
    eliminated: 'Eliminated',
    askingNow: '🎤 Asking now',
    active: 'Active',
    leaveQuestion: 'Leave the game?',
    leaveBody: "Are you sure you want to leave? You'll be removed from this session.",
    stay: 'Stay',
    leave: 'Leave',
    reconnecting: 'Reconnecting…',
    connectionLost: "Connection lost — you're not seeing live updates",
    correctGuessAlert: (guesser, target, word) => `🎉 ${guesser} guessed ${target}'s word: ${word}!`,
    tabQuestions: 'Questions',
    tabNotebook: 'Notebook',
    tabPlayers: 'Players',
    tabChat: 'Chat',
    tabLobby: 'Lobby',
    tabProfile: 'Profile',
    tabWordEntry: 'Word',
    tabResults: 'Results',
    noQuestionsYet: 'No questions yet — ask the first one!',
    autoQuestionExplainer: "Time's up — we asked one for you this time.",
    chatEmpty: 'No messages yet. Say hi! 👋',
    chatPlaceholder: 'Type a message…',
    chatFailed: 'Failed to send — tap to retry',
    newMessages: (n) => n > 1 ? `${n} new messages` : 'New message',
    categorie: 'Category',
    room: 'Room',
    // Guess Modal
    makeAGuessTitle: 'Make a Guess',
    correct: 'Correct! 🎉',
    guessedWord: (name) => `You guessed ${name}'s word!`,
    plusOnePoint: '+1 point!',
    continueBtn: 'Continue',
    wrongGuess: 'Wrong guess!',
    notTheirWord: (name) => `That's not ${name}'s secret word.`,
    close: 'Close',
    whoToGuess: 'Who do you want to guess?',
    noOneLeft: 'No one left to guess!',
    searchOrType: 'Search or type your guess…',
    whatIsTheirWord: "What's their secret word?",
    noMatch: (search) => `No match — your typed guess: "${search}"`,
    submitGuess: 'Submit Guess',
    submitting: 'Submitting…',
    // Notebook
    noOpponents: 'No opponents yet',
    wordRevealedLabel: 'Word revealed!',
    guessedBy: (name) => `Guessed by ${name}`,
    theirHints: 'Their Hints',
    myGuesses: 'My Guesses',
    noClues: 'No clues yet — answers will appear as questions are asked.',
    clues: 'Clues',
    answerYes: '✅ Yes',
    answerNo: '❌ No',
    // Finished
    youWin: '🎉 You Win!',
    gameOver: 'Game Over',
    gameEndedEarly: 'Game Ended Early',
    noCorrectGuesses: 'No one guessed a word this round — no rewards this time.',
    winsWithPoints: (name, pts) => `🏆 ${name} wins with ${pts} point${pts !== 1 ? 's' : ''}!`,
    tiedFirst: (names, pts) => `🏆 Tied 1st place: ${names} with ${pts} pts!`,
    secret: 'Secret',
    pts: 'pts',
    totalPts: (n) => `Total: ${n}`,
    playAgain: 'Play Again (Same Players)',
    settingUp: 'Setting up…',
    waitingForHostRound: 'Waiting for host to start another round…',
    backToHome: 'Back to Home',
    // Profile Settings
    profileSettings: 'Profile Settings',
    signInTitle: 'Save your account',
    signInDesc: 'Sign in to keep an account across devices. Playing works the same either way.',
    signInCta: 'Sign in / Create account',
    registeredAccount: 'Registered Account',
    signOut: 'Sign Out',
    deleteAccount: 'Delete Account',
    deleteProfile: 'Delete Profile',
    deleteAccountDesc: 'Permanently removes your account and all associated game records. This cannot be undone.',
    deleteProfileDesc: 'Removes your local profile name and all associated game records. This cannot be undone.',
    deleteMyAccount: 'Delete My Account',
    deleteMyProfile: 'Delete My Profile',
    areYouSure: 'Are you sure?',
    cannotBeUndone: 'This action cannot be undone.',
    deleteAccountConfirm: 'Your account and all game records will be permanently deleted.',
    deleteProfileConfirm: 'Your display name and all game records linked to this device will be permanently deleted.',
    cancel: 'Cancel',
    yesDelete: 'Yes, Delete',
    deleting: 'Deleting…',
    language: 'Language',
    soundEffects: 'Sound Effects',
    soundEffectsDesc: 'Play sounds for correct guesses, hints and alerts.',
    haptics: 'Haptic Feedback',
    hapticsDesc: 'Feel a vibration for unlocks and key moments (where supported).',
    scrollForMore: 'Swipe for more',
    done: 'Done',
    askedBy: 'Asked by',
    youShort: 'You',
  },
  nl: {
    // Home
    tagline: 'Het Interactieve Raadspel',
    guessLaughWin: 'Raad. Lach. Win.',
    subtitle: 'Raad wat de andere speler(s) kozen, wees de snelste en win!',
    players: '2–12 spelers',
    guessing: 'Raden',
    realtime: 'Real-time',
    whatsYourName: 'Wat is jouw naam?',
    displayNamePlaceholder: 'Jouw weergavenaam',
    letsPlay: 'Spelen!',
    playingAs: 'Speel als',
    online: 'Online',
    change: 'Wijzigen',
    createGame: 'Spel aanmaken',
    createGameDesc: 'Wees de host en daag je vrienden uit!',
    creating: 'Aanmaken...',
    host: 'HOST',
    join: 'MEEDOEN',
    browse: 'BLADEREN',
    gameVisibility: 'ZICHTBAARHEID',
    publicLobby: 'Publiek',
    publicLobbyDesc: 'Iedereen kan meedoen',
    privateLobby: 'Privé',
    privateLobbyDesc: 'Meedoen met code',
    joinGame: 'Meedoen',
    joinGameDesc: 'Voer een kamercode in om mee te doen.',
    roomCodePlaceholder: 'Code',
    openLobbies: 'Bekijk spellen',
    openLobbiesDesc: 'Doe mee met een open spel',
    loading: 'Laden…',
    noOpenLobbies: 'Geen open lobby\'s nu. Maak er een aan!',
    waiting: 'wachten',
    howToPlay: 'Hoe speel je? 🎉',
    howToPlayShort: 'Hoe te spelen',
    settings: 'Instellingen',
    gotIt: 'Begrepen!',
    howToPlaySteps: [
      { title: 'Maak een publieke of privélobby.', body: 'Nodig je vrienden uit of laat anderen meedoen aan jouw publieke spel.' },
      { title: 'Kies een categorie & geheim woord.', body: 'De host kiest een categorie, daarna kiest iedereen zijn eigen geheime woord. Kies een woord dat je goed genoeg kent om vragen over te beantwoorden. Wees eerlijk, vals spelen maakt het minder leuk!' },
      { title: 'Beantwoord de vragen.', body: 'Spelers stellen om beurten Ja/Nee-vragen. Iedereen antwoordt eerlijk op basis van zijn eigen geheime woord.' },
      { title: 'Vul je Notitieboekje.', body: 'Elk antwoord wordt automatisch opgeslagen als aanwijzing. Gebruik deze aanwijzingen om ieders geheime woord te achterhalen.' },
      { title: 'Doe een gok.', body: 'Na elke ronde vragen kan elke speler één gok doen. Een juiste gok levert 1 punt op.' },
      { title: 'Hintronde.', body: 'Elke 5 ronden schrijft iedereen één korte hint over zijn geheime woord om de andere spelers te helpen.' },
      { title: 'Win het spel!', body: 'De speler met de meeste punten aan het einde wint! 🕵️🏆' },
    ],
    // Lobby
    waitingForPlayers: 'Wachten op spelers…',
    roomCode: 'Kamercode',
    shareInvite: 'Uitnodiging delen',
    shareInviteText: (code) => `Doe mee met mijn spel op What's My Pick! Kamercode: ${code}`,
    linkCopied: 'Uitnodiging gekopieerd naar klembord',
    startGame: 'Spel starten',
    starting: 'Starten…',
    startingIn: 'Start over…',
    tapToCancel: 'Tik om te annuleren',
    needTwoPlayers: 'Minstens 2 spelers nodig',
    startWith: (cat) => `Starten — ${cat}`,
    leaveGame: 'Spel verlaten',
    waitingForHost: 'Wachten tot de host een categorie kiest en start…',
    selectCategory: 'Kies een categorie',
    selectedCategory: 'Gekozen categorie',
    changeCategory: 'Wijzig categorie',
    freeCategory: 'Gratis categorie',
    includedWith: (pack) => `Inbegrepen bij ${pack}`,
    chooseCategory: 'Kies een categorie',
    chooseCategorySub: 'Kies één categorie voor dit spel.',
    moreCategories: 'Meer categorieën',
    unlocksLabel: 'Ontgrendelt',
    moreCount: (n) => `+${n} meer`,
    premiumBadge: 'PREMIUM',
    unlockForever: 'Voor altijd ontgrendelen',
    ownedBadge: 'IN BEZIT',
    unlockAll: '🎉 Alles ontgrendelen — $15',
    unlockAllSub: 'Alle pakketten + Aangepast woordenpakket, voor altijd',
    getAll: 'Alles kopen',
    redirecting: 'Doorsturen…',
    unlockFor: (price) => price ? `Ontgrendelen voor ${price}` : 'Ontgrendelen',
    customCategoryLabel: 'Eigen woorden',
    customWordsUnlocked: 'Aangepaste woorden ontgrendeld',
    custom: 'Aangepast',
    // Progression
    profileTitle: 'Profiel',
    collection: 'Collectie',
    shop: 'Winkel',
    challenges: 'Uitdagingen',
    featured: 'Uitgelicht',
    level: 'Level',
    unlocked: 'Ontgrendeld',
    notEnoughPicks: 'Nog niet genoeg Picks — blijf spelen!',
    unlockAtLevel: 'Ontgrendelt op level',
    statGames: 'Spellen',
    statWins: 'Winst',
    statWinRate: 'Winratio',
    statGuesses: 'Gokken',
    statFavorite: 'Favoriete categorie',
    rewardsTitle: 'Beloningen',
    levelUp: 'Level omhoog! Je bent nu level',
    rwComplete: 'Spel voltooid',
    rwGuesses: 'Goed geraden',
    rwWinner: 'Winnaar',
    rwPerfect: 'Perfect spel',
    rwHost: 'Host-bonus',
    rwStreak: 'Winstreak',
    dailyChallenges: 'Dagelijkse uitdagingen',
    weeklyChallenges: 'Wekelijkse uitdagingen',
    confirmUnlock: 'Deze cosmetic ontgrendelen?',
    unlockNow: 'Ontgrendel',
    youHave: 'Je hebt',
    equippedNow: 'Uitgerust!',
    niceBtn: 'Mooi!',
    rotatesDaily: 'Elke dag nieuw',
    todaysShop: 'Winkel van vandaag',
    earnByPlaying: 'Verdien door te spelen',
    collectionEmpty: 'Nog niets — check de winkel van vandaag of verdien beloningen door te spelen!',
    backLabel: 'Terug',
    tapWordToGuess: 'Tik op een woord hierboven om je gok te kiezen',
    errorTitle: 'Er ging iets mis',
    enterYourName: 'Vul je naam in',
    enterRoomCode: 'Vul een roomcode in',
    roomNotFound: 'Room niet gevonden',
    gameAlreadyStarted: 'Het spel is al begonnen',
    checkCodeTryAgain: 'Controleer de code en probeer opnieuw.',
    gameInProgressJoinNext: 'Dit spel is bezig. Je kunt de volgende ronde meedoen!',
    youLeftGame: 'Je hebt het spel verlaten',
    stillGoingRejoin: 'Het spel is nog bezig. Weer meedoen?',
    rejoinGame: 'Weer meedoen',
    playersCount: (n) => `${n} / 12 spelers`,
    lobbyFull: 'Lobby vol',
    inviteHint: 'Tik om de roomcode te kopiëren en deel hem met je vrienden',
    enterWordFirst: 'Vul eerst je woord in',
    pickWordFirst: 'Kies eerst een woord',
    noStatsYet: 'Nog geen profielstatistieken.',
    statLevel: 'Level',
    challengeNames: {
      d_win1: 'Win een spel',
      d_guess2: 'Raad 2 woorden goed',
      d_play3: 'Voltooi 3 spellen',
      d_host1: 'Host een spel',
      d_big1: 'Speel met 4+ spelers',
      w_play10: 'Voltooi 10 spellen',
      w_win5: 'Win 5 spellen',
      s_play40: 'Voltooi 40 spellen',
      s_guess25: '25 goede gokken',
      s_win15: 'Win 15 spellen',
    },
    roomFull: 'Room is vol (max 12)',
    failedToJoin: 'Meedoen mislukt',
    failedToCreate: 'Spel aanmaken mislukt',
    pickCategoryFirst: 'Kies eerst een categorie',
    profileDeleted: 'Profiel verwijderd',
    profileDeletedDesc: 'Je lokale profiel en spelgegevens zijn verwijderd.',
    accountDeleted: 'Account verwijderd',
    accountDeletedDesc: 'Je account en spelgegevens zijn verwijderd.',
    deleteFailed: 'Verwijderen mislukt',
    newBadge: 'NIEUW',
    statStreak: 'Reeks',
    removeFromGame: 'Verwijder uit spel',
    removedByHost: 'De host heeft je uit het spel verwijderd',
    playerJoined: (name) => `${name} is erbij gekomen`,
    playerLeft: (name) => `${name} heeft het spel verlaten`,
    sessionExpired: 'Je sessie is verlopen — log opnieuw in om je account te blijven synchroniseren',
    collectionsLabel: 'Collecties',
    collectionReward: 'Set-beloning',
    betaExclusive: 'Alleen voor beta-testers',
    completeCollectionHint: 'Voltooi de collectie om dit te verdienen',
    collectionComplete: 'Collectie compleet!',
    completionReward: 'Voltooiingsbeloning',
    purchaseUnavailable: 'Aankopen zijn beschikbaar in de iOS-app',
    purchaseFailed: 'Aankoop mislukt — probeer opnieuw',
    purchasing: 'Bezig met kopen…',
    restorePurchases: 'Aankopen herstellen',
    restorePurchasesDesc: 'Haal eerder gekochte packs terug op dit apparaat.',
    restoreBtn: 'Herstel',
    restoreDone: (n) => n > 0 ? `${n} pack${n > 1 ? 's' : ''} hersteld` : 'Niets om te herstellen',
    restoreFailed: 'Herstellen mislukt — controleer je verbinding en probeer opnieuw',
    supportFaq: 'Hulp & veelgestelde vragen',
    gameInProgress: 'Spel bezig',
    mutePlayer: 'Speler dempen',
    unmutePlayer: 'Dempen opheffen',
    away: 'Afwezig',
    hostLobby: (name) => `Lobby van ${name}`,
    shareResult: 'Delen',
    shareResultText: (won, rank, total) => won
      ? 'Ik heb net een ronde What\'s My Pick! gewonnen 🏆 Denk je dat je mij kunt verslaan?'
      : `Ik werd #${rank} van ${total} in What's My Pick! Kun jij het beter?`,
    // Share win card
    scPerfect: 'PERFECT!',
    scVictory: 'GEWONNEN!',
    scPlace: (rank) => `#${rank}E PLAATS`,
    scWordsGuessed: 'WOORDEN GERADEN',
    scStreakChip: (n) => `🔥 ${n} OP RIJ`,
    shareCardCta: 'Delen',
    shareCardSaved: 'Afbeelding opgeslagen',
    newStockIn: (time) => `Nieuwe voorraad over ${time}`,
    playerFallback: 'Speler',
    pageNotFound: 'Pagina niet gevonden',
    pageNotFoundBody: (page) => `De pagina "${page}" bestaat niet.`,
    icloudBackedUp: 'Voortgang geback-upt naar iCloud',
    icloudNotBackedUp: 'Geen back-up — schakel iCloud in voor deze app om je voortgang te beschermen',
    reportPlayer: 'Speler rapporteren',
    reportThanks: 'Gerapporteerd — bedankt',
    privacyPolicy: 'Privacybeleid',
    editName: 'Naam wijzigen',
    nameSaved: 'Naam bijgewerkt!',
    saveBtn: 'Opslaan',
    equippedLabel: 'Uitgeruste cosmetics',
    changeInProfile: 'Wijzig in profiel →',
    slotLabels: { emblem: 'Embleem', border: 'Rand', banner: 'Banner', title: 'Titel', nameColor: 'Naamstijl' },
    syncOk: 'Cloudsync actief — andere spelers zien jouw cosmetics',
    syncMissing: 'Cloudsync niet beschikbaar — andere spelers zien jouw cosmetics niet. Voer supabase/migrations/0002_player_profiles.sql uit in de Supabase SQL-editor en herlaad de app.',
    seasonFootnote: 'Seizoensbeloningen zijn exclusief en nooit te koop.',
    dailyReward: 'Dagelijkse beloning',
    dayStreak: 'dagen streak',
    // WordEntry
    chooseSecretWord: 'Kies je geheime woord',
    category: 'Categorie',
    typeAnyWord: 'Typ elk woord voor anderen om te raden',
    enterSecretWord: 'Voer je geheime woord in…',
    keepItSecret: 'Houd het geheim! Andere spelers zullen het proberen te raden.',
    change2: 'Wijzigen',
    search: (cat) => `Zoek ${cat}…`,
    noResults: 'Geen resultaten',
    lockIn: 'Mijn woord vergrendelen',
    lockingIn: 'Vergrendelen…',
    wordLockedIn: 'Woord vergrendeld!',
    waitingForOthers: 'Wachten op anderen…',
    wordTimeoutKicked: 'Tijd is om — je hebt geen woord op tijd gekozen',
    wordTimeoutLobby: 'Tijd is om — niet genoeg spelers om door te gaan, terug naar de lobby',
    everyoneReady: 'Iedereen klaar — Starten!',
    you: 'JIJ',
    // Playing
    myWord: 'Mijn woord',
    hintRound: '💡 Hintronde!',
    hintRoundSub: 'Na elke 5 vragen geeft iedereen een hint over zijn eigen woord. Vragen hervatten zodra alle hints zijn ingediend.',
    hintSubmitted: '✅ Hint ingediend! Wachten op anderen…',
    allHintsIn: '✅ Alle hints zijn binnen! Bekijk ze in je Notitieboekje tabblad.',
    giveHint: 'Geef een hint over je geheime woord (zeg het niet direct!)',
    hintPlaceholder: 'Bijv. Het leeft in de oceaan…',
    share: 'Delen',
    waitingForHints: 'Wachten op andere spelers om hun hints in te dienen…',
    allHintsSubmitted: '💡 Alle hints ingediend! Bekijk ze in je Notitieboekje tabblad.',
    waitingForAnswers: 'Wachten tot iedereen geantwoord heeft…',
    answerThisQuestion: 'Beantwoord deze vraag voor JOUW woord:',
    yes: '✅ Ja',
    no: '❌ Nee',
    yourTurnToAsk: 'Jouw beurt om te vragen!',
    autoAsking: 'Auto-vragen…',
    askPlaceholder: 'Stel een ja/nee-vraag…',
    askQuestion: 'Vraag stellen',
    skipToAI: 'Auto',
    skipTitle: 'Overslaan — laat AI vragen',
    isTurnToAsk: (name) => `${name} is aan de beurt`,
    guessIn: (n) => `Raden over ${n} ${n === 1 ? 'vraag' : 'vragen'}`,
    guessOthers: '🎯 Jouw woord gevonden, raad anderen!',
    makeAGuess: 'Doe een gok',
    endGame: 'Spel beëindigen',
    allPlayers: 'Alle spelers',
    wordRevealed: (word) => `Geraden! (${word})`,
    eliminated: 'Uitgeschakeld',
    askingNow: '🎤 Vraagt nu',
    active: 'Actief',
    leaveQuestion: 'Spel verlaten?',
    leaveBody: 'Weet je zeker dat je wilt vertrekken? Je wordt verwijderd uit deze sessie.',
    stay: 'Blijven',
    leave: 'Verlaten',
    reconnecting: 'Opnieuw verbinden…',
    connectionLost: 'Verbinding verbroken — je ziet geen live updates',
    correctGuessAlert: (guesser, target, word) => `🎉 ${guesser} raadde het woord van ${target}: ${word}!`,
    tabQuestions: 'Vragen',
    tabNotebook: 'Notities',
    tabPlayers: 'Spelers',
    tabChat: 'Chat',
    tabLobby: 'Lobby',
    tabProfile: 'Profiel',
    tabWordEntry: 'Woord',
    tabResults: 'Resultaat',
    noQuestionsYet: 'Nog geen vragen — stel de eerste!',
    autoQuestionExplainer: 'Tijd is om — we hebben er deze keer een voor je gesteld.',
    chatEmpty: 'Nog geen berichten. Zeg hoi! 👋',
    chatPlaceholder: 'Typ een bericht…',
    chatFailed: 'Versturen mislukt — tik om opnieuw te proberen',
    newMessages: (n) => n > 1 ? `${n} nieuwe berichten` : 'Nieuw bericht',
    categorie: 'Categorie',
    room: 'Kamer',
    // Guess Modal
    makeAGuessTitle: 'Doe een gok',
    correct: 'Correct! 🎉',
    guessedWord: (name) => `Je raadde het woord van ${name}!`,
    plusOnePoint: '+1 punt!',
    continueBtn: 'Doorgaan',
    wrongGuess: 'Fout!',
    notTheirWord: (name) => `Dat is niet het geheime woord van ${name}.`,
    close: 'Sluiten',
    whoToGuess: 'Wie wil je raden?',
    noOneLeft: 'Niemand meer te raden!',
    searchOrType: 'Zoeken of gok typen…',
    whatIsTheirWord: 'Wat is hun geheime woord?',
    noMatch: (search) => `Geen resultaat — jouw gok: "${search}"`,
    submitGuess: 'Gok indienen',
    submitting: 'Indienen…',
    // Notebook
    noOpponents: 'Nog geen tegenstanders',
    wordRevealedLabel: 'Woord onthuld!',
    guessedBy: (name) => `Geraden door ${name}`,
    theirHints: 'Hun hints',
    myGuesses: 'Mijn gokken',
    noClues: 'Nog geen aanwijzingen — antwoorden verschijnen naarmate er vragen worden gesteld.',
    clues: 'Aanwijzingen',
    answerYes: '✅ Ja',
    answerNo: '❌ Nee',
    // Finished
    youWin: '🎉 Jij wint!',
    gameOver: 'Spel afgelopen',
    gameEndedEarly: 'Spel vroegtijdig beëindigd',
    noCorrectGuesses: 'Niemand raadde een woord deze ronde — geen beloningen dit keer.',
    winsWithPoints: (name, pts) => `🏆 ${name} wint met ${pts} punt${pts !== 1 ? 'en' : ''}!`,
    tiedFirst: (names, pts) => `🏆 Gelijk 1e: ${names} met ${pts} ptn!`,
    totalPts: (n) => `Totaal: ${n}`,
    secret: 'Geheim',
    pts: 'ptn',
    playAgain: 'Opnieuw spelen (zelfde spelers)',
    settingUp: 'Instellen…',
    waitingForHostRound: 'Wachten op de host voor een nieuwe ronde…',
    backToHome: 'Terug naar Home',
    // Profile Settings
    profileSettings: 'Profielinstellingen',
    signInTitle: 'Account bewaren',
    signInDesc: 'Log in om een account op meerdere apparaten te gebruiken. Spelen werkt hetzelfde, met of zonder account.',
    signInCta: 'Inloggen / account aanmaken',
    registeredAccount: 'Geregistreerd account',
    signOut: 'Uitloggen',
    deleteAccount: 'Account verwijderen',
    deleteProfile: 'Profiel verwijderen',
    deleteAccountDesc: 'Verwijdert je account en alle bijbehorende spelrecords permanent. Dit kan niet ongedaan worden gemaakt.',
    deleteProfileDesc: 'Verwijdert je lokale profielnaam en alle bijbehorende spelrecords. Dit kan niet ongedaan worden gemaakt.',
    deleteMyAccount: 'Mijn account verwijderen',
    deleteMyProfile: 'Mijn profiel verwijderen',
    areYouSure: 'Weet je het zeker?',
    cannotBeUndone: 'Deze actie kan niet ongedaan worden gemaakt.',
    deleteAccountConfirm: 'Je account en alle spelrecords worden permanent verwijderd.',
    deleteProfileConfirm: 'Je weergavenaam en alle spelrecords op dit apparaat worden permanent verwijderd.',
    cancel: 'Annuleren',
    yesDelete: 'Ja, verwijderen',
    deleting: 'Verwijderen…',
    language: 'Taal',
    soundEffects: 'Geluidseffecten',
    soundEffectsDesc: 'Speel geluiden bij juiste gokken, hints en meldingen.',
    haptics: 'Trilfeedback',
    hapticsDesc: 'Voel een trilling bij unlocks en belangrijke momenten (indien ondersteund).',
    scrollForMore: 'Veeg voor meer',
    done: 'Klaar',
    askedBy: 'Gevraagd door',
    youShort: 'Jij',
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem(LS_KEY) || 'en');

  const switchLang = (l) => {
    setLang(l);
    localStorage.setItem(LS_KEY, l);
  };

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}