import React, { createContext, useContext, useState, useEffect } from 'react';

const LS_KEY = 'app_language';

const translations = {
  en: {
    // Home
    tagline: 'The interactive guessing game',
    subtitle: "Guess what the other player(s) picked, be the fastest and win!",
    players: '2–12 players',
    guessing: 'Guessing',
    realtime: 'Real-time',
    whatsYourName: "What's your name?",
    displayNamePlaceholder: 'Your display name',
    letsPlay: "Let's Play!",
    playingAs: 'Playing as',
    change: 'change',
    createGame: 'Create Game',
    creating: 'Creating...',
    publicLobby: 'Public lobby — anyone can join',
    privateLobby: 'Private lobby (code only)',
    roomCodePlaceholder: 'ROOM CODE',
    openLobbies: 'Open Lobbies',
    loading: 'Loading…',
    noOpenLobbies: 'No open lobbies right now. Create one!',
    waiting: 'waiting',
    howToPlay: 'How to Play 🎉',
    gotIt: 'Got it!',
    howToPlaySteps: [
      { title: 'Create a Public or Private Lobby.', body: 'Invite your friends or let others join your public game.' },
      { title: 'Pick a category & secret word.', body: 'The host picks a category, then everyone chooses their own secret word. Pick a word you know well enough to answer questions about. Be honest, cheating takes away the fun!' },
      { title: 'Answer the questions.', body: 'Players take turns asking Yes/No questions. Everyone answers honestly based on their own secret word.' },
      { title: 'Fill your Notebook.', body: "Every answer is automatically saved as a clue for each player. Use these clues to figure out everyone's secret word." },
      { title: 'Make a guess.', body: 'After each round of questions, every player can make one guess. A correct guess earns you 1 point.' },
      { title: 'Hint Round.', body: 'Every 5 rounds, everyone writes one short hint about their secret word to help the other players.' },
      { title: 'Win the game!', body: 'The player with the most points at the end wins! 🕵️🏆' },
    ],
    // Lobby
    waitingForPlayers: 'Waiting for players to join…',
    roomCode: 'Room Code',
    startGame: 'Start Game',
    starting: 'Starting…',
    startWith: (cat) => `Start — ${cat}`,
    leaveGame: 'Leave Game',
    waitingForHost: 'Waiting for the host to pick a category and start…',
    selectCategory: 'Select a Category',
    unlockAll: '🎉 Unlock Everything — $15',
    unlockAllSub: 'All packs + Custom Word Pack, forever',
    getAll: 'Get All',
    redirecting: 'Redirecting…',
    unlockFor: 'Unlock for $2.99',
    customWordPack: 'Custom Word Pack — $2.99',
    customWordPackSub: 'Type any word you want as your secret word — no limits',
    customWordsUnlocked: 'Custom Words Unlocked',
    custom: 'Custom',
    // WordEntry
    chooseSecretWord: 'Choose Your Secret Word',
    category: 'Category',
    typeAnyWord: 'Type any word for others to guess',
    enterSecretWord: 'Enter your secret word…',
    keepItSecret: "Keep it secret! Other players will try to guess it.",
    change2: 'Change',
    search: (cat) => `Search ${cat}…`,
    noResults: 'No results',
    lockIn: 'Lock In My Word',
    lockingIn: 'Locking in…',
    wordLockedIn: 'Word locked in!',
    waitingForOthers: 'Waiting for others…',
    everyoneReady: "Everyone's ready — Start!",
    you: 'YOU',
    // Playing
    myWord: 'My Word',
    hintRound: '💡 Hint Round!',
    hintRoundSub: 'After every 5 questions, everyone gives a hint about their own word. Questions resume once all hints are in.',
    hintSubmitted: '✅ Hint submitted! Waiting for others…',
    allHintsIn: '✅ All hints are in! Check everyone\'s hints in your Notebook tab.',
    giveHint: 'Give a hint about your secret word (don\'t say it directly!)',
    hintPlaceholder: 'E.g. It lives in the ocean…',
    share: 'Share',
    waitingForHints: 'Waiting for other players to submit their hints…',
    allHintsSubmitted: '💡 All hints submitted! Check them in your Notebook tab.',
    waitingForAnswers: 'Waiting for everyone to answer…',
    answerThisQuestion: 'Answer this question for YOUR word:',
    yes: '✅ Yes',
    no: '❌ No',
    yourTurnToAsk: 'Your turn to ask!',
    autoAsking: 'Auto-asking…',
    askPlaceholder: 'Ask a yes/no question…',
    askQuestion: 'Ask Question',
    skipToAI: 'Auto',
    skipTitle: 'Skip — let AI ask',
    isTurnToAsk: (name) => `${name}'s turn to ask`,
    guessIn: (n) => `Guess in ${n} question(s)`,
    guessOthers: '🎯 Your word was found, guess others!',
    makeAGuess: 'Make a Guess',
    endGame: 'End Game',
    allPlayers: 'All Players',
    wordRevealed: (word) => `Guessed! (${word})`,
    eliminated: 'Eliminated',
    askingNow: '🎤 Asking now',
    active: 'Active',
    leaveQuestion: 'Leave the game?',
    leaveBody: "Are you sure you want to leave? You'll be removed from this session.",
    stay: 'Stay',
    leave: 'Leave',
    correctGuessAlert: (guesser, target, word) => `🎉 ${guesser} guessed ${target}'s word: ${word}!`,
    tabQuestions: 'Questions',
    tabNotebook: 'Notebook',
    tabPlayers: 'Players',
    tabChat: 'Chat',
    categorie: 'Category',
    room: 'Room',
    // Guess Modal
    makeAGuessTitle: 'Make a Guess',
    correct: 'Correct! 🎉',
    guessedWord: (name) => `You guessed ${name}'s word!`,
    plusOnePoint: '+1 point!',
    continueBtn: 'Continue',
    wrongGuess: 'Wrong guess!',
    notTheirWord: (name) => `That's not ${name}'s secret word.`,
    close: 'Close',
    whoToGuess: 'Who do you want to guess?',
    noOneLeft: 'No one left to guess!',
    searchOrType: 'Search or type your guess…',
    whatIsTheirWord: "What's their secret word?",
    noMatch: (search) => `No match — your typed guess: "${search}"`,
    submitGuess: 'Submit Guess',
    submitting: 'Submitting…',
    // Notebook
    noOpponents: 'No opponents yet',
    wordRevealedLabel: 'Word revealed!',
    guessedBy: (name) => `Guessed by ${name}`,
    theirHints: 'Their Hints',
    myGuesses: 'My Guesses',
    noClues: 'No clues yet — answers will appear as questions are asked.',
    clues: 'Clues',
    answerYes: '✅ Yes',
    answerNo: '❌ No',
    // Finished
    youWin: '🎉 You Win!',
    gameOver: 'Game Over',
    winsWithPoints: (name, pts) => `🏆 ${name} wins with ${pts} point${pts !== 1 ? 's' : ''}!`,
    tiedFirst: (names, pts) => `🏆 Tied 1st place: ${names} with ${pts} pts!`,
    secret: 'Secret',
    pts: 'pts',
    playAgain: 'Play Again (Same Players)',
    settingUp: 'Setting up…',
    waitingForHostRound: 'Waiting for host to start another round…',
    backToHome: 'Back to Home',
    // Profile Settings
    profileSettings: 'Profile Settings',
    signInTitle: 'Save your account',
    signInDesc: 'Sign in to keep an account across devices. Playing works the same either way.',
    signInCta: 'Sign in / Create account',
    registeredAccount: 'Registered Account',
    signOut: 'Sign Out',
    deleteAccount: 'Delete Account',
    deleteProfile: 'Delete Profile',
    deleteAccountDesc: 'Permanently removes your account and all associated game records. This cannot be undone.',
    deleteProfileDesc: 'Removes your local profile name and all associated game records. This cannot be undone.',
    deleteMyAccount: 'Delete My Account',
    deleteMyProfile: 'Delete My Profile',
    areYouSure: 'Are you sure?',
    cannotBeUndone: 'This action cannot be undone.',
    deleteAccountConfirm: 'Your account and all game records will be permanently deleted.',
    deleteProfileConfirm: 'Your display name and all game records linked to this device will be permanently deleted.',
    cancel: 'Cancel',
    yesDelete: 'Yes, Delete',
    deleting: 'Deleting…',
    language: 'Language',
    soundEffects: 'Sound Effects',
    soundEffectsDesc: 'Play sounds for correct guesses, hints and alerts.',
    scrollForMore: 'Swipe for more',
    done: 'Done',
    askedBy: 'Asked by',
    youShort: 'You',
  },
  nl: {
    // Home
    tagline: 'Het interactieve raadspel',
    subtitle: 'Raad wat de andere speler(s) kozen, wees de snelste en win!',
    players: '2–12 spelers',
    guessing: 'Raden',
    realtime: 'Real-time',
    whatsYourName: 'Wat is jouw naam?',
    displayNamePlaceholder: 'Jouw weergavenaam',
    letsPlay: 'Spelen!',
    playingAs: 'Speel als',
    change: 'wijzigen',
    createGame: 'Spel aanmaken',
    creating: 'Aanmaken...',
    publicLobby: 'Publieke lobby — iedereen kan meedoen',
    privateLobby: 'Privélobby (alleen met code)',
    roomCodePlaceholder: 'KAMERCODE',
    openLobbies: 'Open Lobby\'s',
    loading: 'Laden…',
    noOpenLobbies: 'Geen open lobby\'s nu. Maak er een aan!',
    waiting: 'wachten',
    howToPlay: 'Hoe speel je? 🎉',
    gotIt: 'Begrepen!',
    howToPlaySteps: [
      { title: 'Maak een publieke of privélobby.', body: 'Nodig je vrienden uit of laat anderen meedoen aan jouw publieke spel.' },
      { title: 'Kies een categorie & geheim woord.', body: 'De host kiest een categorie, daarna kiest iedereen zijn eigen geheime woord. Kies een woord dat je goed genoeg kent om vragen over te beantwoorden. Wees eerlijk, vals spelen maakt het minder leuk!' },
      { title: 'Beantwoord de vragen.', body: 'Spelers stellen om beurten Ja/Nee-vragen. Iedereen antwoordt eerlijk op basis van zijn eigen geheime woord.' },
      { title: 'Vul je Notitieboekje.', body: 'Elk antwoord wordt automatisch opgeslagen als aanwijzing. Gebruik deze aanwijzingen om ieders geheime woord te achterhalen.' },
      { title: 'Doe een gok.', body: 'Na elke ronde vragen kan elke speler één gok doen. Een juiste gok levert 1 punt op.' },
      { title: 'Hintronde.', body: 'Elke 5 ronden schrijft iedereen één korte hint over zijn geheime woord om de andere spelers te helpen.' },
      { title: 'Win het spel!', body: 'De speler met de meeste punten aan het einde wint! 🕵️🏆' },
    ],
    // Lobby
    waitingForPlayers: 'Wachten op spelers…',
    roomCode: 'Kamercode',
    startGame: 'Spel starten',
    starting: 'Starten…',
    startWith: (cat) => `Starten — ${cat}`,
    leaveGame: 'Spel verlaten',
    waitingForHost: 'Wachten tot de host een categorie kiest en start…',
    selectCategory: 'Kies een categorie',
    unlockAll: '🎉 Alles ontgrendelen — $15',
    unlockAllSub: 'Alle pakketten + Aangepast woordenpakket, voor altijd',
    getAll: 'Alles kopen',
    redirecting: 'Doorsturen…',
    unlockFor: 'Ontgrendelen voor $2.99',
    customWordPack: 'Aangepast woordenpakket — $2.99',
    customWordPackSub: 'Typ elk woord dat je wilt als je geheime woord — geen limieten',
    customWordsUnlocked: 'Aangepaste woorden ontgrendeld',
    custom: 'Aangepast',
    // WordEntry
    chooseSecretWord: 'Kies je geheime woord',
    category: 'Categorie',
    typeAnyWord: 'Typ elk woord voor anderen om te raden',
    enterSecretWord: 'Voer je geheime woord in…',
    keepItSecret: 'Houd het geheim! Andere spelers zullen het proberen te raden.',
    change2: 'Wijzigen',
    search: (cat) => `Zoek ${cat}…`,
    noResults: 'Geen resultaten',
    lockIn: 'Mijn woord vergrendelen',
    lockingIn: 'Vergrendelen…',
    wordLockedIn: 'Woord vergrendeld!',
    waitingForOthers: 'Wachten op anderen…',
    everyoneReady: 'Iedereen klaar — Starten!',
    you: 'JIJ',
    // Playing
    myWord: 'Mijn woord',
    hintRound: '💡 Hintronde!',
    hintRoundSub: 'Na elke 5 vragen geeft iedereen een hint over zijn eigen woord. Vragen hervatten zodra alle hints zijn ingediend.',
    hintSubmitted: '✅ Hint ingediend! Wachten op anderen…',
    allHintsIn: '✅ Alle hints zijn binnen! Bekijk ze in je Notitieboekje tabblad.',
    giveHint: 'Geef een hint over je geheime woord (zeg het niet direct!)',
    hintPlaceholder: 'Bijv. Het leeft in de oceaan…',
    share: 'Delen',
    waitingForHints: 'Wachten op andere spelers om hun hints in te dienen…',
    allHintsSubmitted: '💡 Alle hints ingediend! Bekijk ze in je Notitieboekje tabblad.',
    waitingForAnswers: 'Wachten tot iedereen geantwoord heeft…',
    answerThisQuestion: 'Beantwoord deze vraag voor JOUW woord:',
    yes: '✅ Ja',
    no: '❌ Nee',
    yourTurnToAsk: 'Jouw beurt om te vragen!',
    autoAsking: 'Auto-vragen…',
    askPlaceholder: 'Stel een ja/nee-vraag…',
    askQuestion: 'Vraag stellen',
    skipToAI: 'Auto',
    skipTitle: 'Overslaan — laat AI vragen',
    isTurnToAsk: (name) => `${name} is aan de beurt`,
    guessIn: (n) => `Raden over ${n} vraag/vragen`,
    guessOthers: '🎯 Jouw woord gevonden, raad anderen!',
    makeAGuess: 'Doe een gok',
    endGame: 'Spel beëindigen',
    allPlayers: 'Alle spelers',
    wordRevealed: (word) => `Geraden! (${word})`,
    eliminated: 'Uitgeschakeld',
    askingNow: '🎤 Vraagt nu',
    active: 'Actief',
    leaveQuestion: 'Spel verlaten?',
    leaveBody: 'Weet je zeker dat je wilt vertrekken? Je wordt verwijderd uit deze sessie.',
    stay: 'Blijven',
    leave: 'Verlaten',
    correctGuessAlert: (guesser, target, word) => `🎉 ${guesser} raadde het woord van ${target}: ${word}!`,
    tabQuestions: 'Vragen',
    tabNotebook: 'Notities',
    tabPlayers: 'Spelers',
    tabChat: 'Chat',
    categorie: 'Categorie',
    room: 'Kamer',
    // Guess Modal
    makeAGuessTitle: 'Doe een gok',
    correct: 'Correct! 🎉',
    guessedWord: (name) => `Je raadde het woord van ${name}!`,
    plusOnePoint: '+1 punt!',
    continueBtn: 'Doorgaan',
    wrongGuess: 'Fout!',
    notTheirWord: (name) => `Dat is niet het geheime woord van ${name}.`,
    close: 'Sluiten',
    whoToGuess: 'Wie wil je raden?',
    noOneLeft: 'Niemand meer te raden!',
    searchOrType: 'Zoeken of gok typen…',
    whatIsTheirWord: 'Wat is hun geheime woord?',
    noMatch: (search) => `Geen resultaat — jouw gok: "${search}"`,
    submitGuess: 'Gok indienen',
    submitting: 'Indienen…',
    // Notebook
    noOpponents: 'Nog geen tegenstanders',
    wordRevealedLabel: 'Woord onthuld!',
    guessedBy: (name) => `Geraden door ${name}`,
    theirHints: 'Hun hints',
    myGuesses: 'Mijn gokken',
    noClues: 'Nog geen aanwijzingen — antwoorden verschijnen naarmate er vragen worden gesteld.',
    clues: 'Aanwijzingen',
    answerYes: '✅ Ja',
    answerNo: '❌ Nee',
    // Finished
    youWin: '🎉 Jij wint!',
    gameOver: 'Spel afgelopen',
    winsWithPoints: (name, pts) => `🏆 ${name} wint met ${pts} punt${pts !== 1 ? 'en' : ''}!`,
    tiedFirst: (names, pts) => `🏆 Gelijk 1e: ${names} met ${pts} ptn!`,
    secret: 'Geheim',
    pts: 'ptn',
    playAgain: 'Opnieuw spelen (zelfde spelers)',
    settingUp: 'Instellen…',
    waitingForHostRound: 'Wachten op de host voor een nieuwe ronde…',
    backToHome: 'Terug naar Home',
    // Profile Settings
    profileSettings: 'Profielinstellingen',
    signInTitle: 'Account bewaren',
    signInDesc: 'Log in om een account op meerdere apparaten te gebruiken. Spelen werkt hetzelfde, met of zonder account.',
    signInCta: 'Inloggen / account aanmaken',
    registeredAccount: 'Geregistreerd account',
    signOut: 'Uitloggen',
    deleteAccount: 'Account verwijderen',
    deleteProfile: 'Profiel verwijderen',
    deleteAccountDesc: 'Verwijdert je account en alle bijbehorende spelrecords permanent. Dit kan niet ongedaan worden gemaakt.',
    deleteProfileDesc: 'Verwijdert je lokale profielnaam en alle bijbehorende spelrecords. Dit kan niet ongedaan worden gemaakt.',
    deleteMyAccount: 'Mijn account verwijderen',
    deleteMyProfile: 'Mijn profiel verwijderen',
    areYouSure: 'Weet je het zeker?',
    cannotBeUndone: 'Deze actie kan niet ongedaan worden gemaakt.',
    deleteAccountConfirm: 'Je account en alle spelrecords worden permanent verwijderd.',
    deleteProfileConfirm: 'Je weergavenaam en alle spelrecords op dit apparaat worden permanent verwijderd.',
    cancel: 'Annuleren',
    yesDelete: 'Ja, verwijderen',
    deleting: 'Verwijderen…',
    language: 'Taal',
    soundEffects: 'Geluidseffecten',
    soundEffectsDesc: 'Speel geluiden bij juiste gokken, hints en meldingen.',
    scrollForMore: 'Veeg voor meer',
    done: 'Klaar',
    askedBy: 'Gevraagd door',
    youShort: 'Jij',
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem(LS_KEY) || 'en');

  const switchLang = (l) => {
    setLang(l);
    localStorage.setItem(LS_KEY, l);
  };

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}