// Category-specific yes/no question bank for "What's my pick?".
// Each category has its own tailored set, so every question makes sense.
// The function picks a random unused question from the matching category,
// falling back to a small universal set for unknown categories.

export const QUESTION_BANK_BY_CATEGORY = {
  // ── Animals ─────────────────────────────────────────────────────────────
  Pets: [
    'Is it a mammal?', 'Is it a dog?', 'Is it a cat?', 'Is it small?', 'Is it bigger than 10 kg?',
    'Does it have fur?', 'Does it have feathers?', 'Does it have scales?', 'Can it fly?', 'Can it swim?',
    'Can it be trained?', 'Does it bark?', 'Does it meow?', 'Does it purr?', 'Does it chirp?',
    'Does it squeak?', 'Is it noisy?', 'Is it quiet?', 'Is it exotic?', 'Is it a reptile?',
    'Is it a rodent?', 'Is it a bird?', 'Is it a fish?', 'Is it a rabbit?', 'Is it a guinea pig?',
    'Is it a hamster?', 'Is it a lizard?', 'Is it a snake?', 'Is it a turtle?', 'Is it a parrot?',
    'Does it live in a cage?', 'Does it live in an aquarium?', 'Does it live outdoors?', 'Does it shed?', 'Does it eat meat?',
    'Does it eat seeds?', 'Does it eat hay?', 'Can it be put on a leash?', 'Is it nocturnal?', 'Does it hibernate?',
    'Is it expensive to keep?', 'Does it live more than 10 years?', 'Is it good with children?', 'Is it territorial?', 'Does it have a long tail?',
    'Does it have whiskers?', 'Does it have claws?', 'Is it a popular pet?', 'Does it purr or chirp?', 'Can it learn tricks?',
  ],
  'Wild Animals': [
    'Is it a mammal?', 'Is it a carnivore?', 'Is it a herbivore?', 'Is it an omnivore?', 'Does it live in Africa?',
    'Does it live in Asia?', 'Does it live in Europe?', 'Does it live in the Americas?', 'Does it live in Australia?', 'Does it live in the jungle?',
    'Does it live in the savanna?', 'Does it live in the desert?', 'Does it live in the mountains?', 'Does it live in the forest?', 'Is it endangered?',
    'Is it bigger than a human?', 'Is it bigger than a car?', 'Is it smaller than a cat?', 'Does it have fur?', 'Does it have stripes?',
    'Does it have spots?', 'Does it have a mane?', 'Does it have a long neck?', 'Does it have a trunk?', 'Does it have horns?',
    'Does it have antlers?', 'Does it have a tail?', 'Can it climb trees?', 'Can it swim?', 'Can it fly?',
    'Is it nocturnal?', 'Does it hunt at night?', 'Does it live in groups?', 'Does it live alone?', 'Is it fast?',
    'Is it slow?', 'Is it a predator?', 'Is it a big cat?', 'Is it a primate?', 'Is it a marsupial?',
    'Does it eat fish?', 'Does it hibernate?', 'Does it have sharp teeth?', 'Is it venomous?', 'Is it a pack animal?',
    'Does it have a strong bite?', 'Can it jump far?', 'Does it make a loud sound?', 'Is it camouflaged?', 'Is it famous?',
  ],
  'Farm Animals': [
    'Is it a mammal?', 'Does it give milk?', 'Does it lay eggs?', 'Does it give wool?', 'Is it raised for meat?',
    'Is it bigger than a dog?', 'Is it bigger than a human?', 'Is it small?', 'Does it have hooves?', 'Does it have feathers?',
    'Does it have fur?', 'Does it have horns?', 'Does it have a beak?', 'Does it have a mane?', 'Does it have a long tail?',
    'Does it live in a barn?', 'Does it live in a field?', 'Does it graze on grass?', 'Does it eat grain?', 'Does it eat hay?',
    'Does it make milk for humans?', 'Can you ride it?', 'Can it pull a cart?', 'Is it a common farm animal?', 'Is it noisy?',
    'Does it cluck?', 'Does it moo?', 'Does it oink?', 'Does it bleat?', 'Does it neigh?',
    'Is it kept in a coop?', 'Is it kept in a pen?', 'Does it lay more than one egg a day?', 'Is it white?', 'Is it brown?',
    'Is it black and white?', 'Does it have a beak?', 'Does it have a comb?', 'Does it crow at dawn?', 'Is it a bird?',
    'Is it a ruminant?', 'Does it produce something humans use?', 'Does it need a lot of space?', 'Is it friendly to humans?', 'Is it a large animal?',
  ],
  'Sea Animals': [
    'Is it a mammal?', 'Is it a fish?', 'Is it a crustacean?', 'Is it a mollusk?', 'Is it a predator?',
    'Is it bigger than a human?', 'Is it bigger than a car?', 'Is it very small?', 'Does it have fins?', 'Does it have tentacles?',
    'Does it have a shell?', 'Does it have scales?', 'Does it have gills?', 'Does it have a blowhole?', 'Does it have a tail?',
    'Does it have teeth?', 'Does it have sharp teeth?', 'Does it have a long body?', 'Is it dangerous to humans?', 'Is it venomous?',
    'Does it live in the deep sea?', 'Does it live near the surface?', 'Does it live on the seabed?', 'Does it live in a reef?', 'Does it live in cold water?',
    'Does it live in warm water?', 'Is it brightly coloured?', 'Is it camouflaged?', 'Is it endangered?', 'Does it swim in schools?',
    'Does it swim alone?', 'Is it fast?', 'Is it slow?', 'Can it change colour?', 'Does it glow?',
    'Does it produce light?', 'Does it have a sting?', 'Does it have eight arms?', 'Does it squirt ink?', 'Does it have a hard shell?',
    'Is it a shark?', 'Is it a whale or dolphin?', 'Is it a popular aquarium fish?', 'Does it eat plankton?', 'Is it a bottom feeder?',
  ],
  Birds: [
    'Can it fly?', 'Is it small?', 'Is it large?', 'Is it colourful?', 'Is it a bird of prey?',
    'Is it nocturnal?', 'Does it have bright feathers?', 'Does it have a long beak?', 'Does it have webbed feet?', 'Does it have a crest?',
    'Does it live near water?', 'Does it live in the forest?', 'Does it live in cities?', 'Does it migrate?', 'Does it sing?',
    'Does it chirp?', 'Does it squawk?', 'Does it hoot?', 'Does it screech?', 'Does it mimic sounds?',
    'Is it a predator?', 'Is it a pet?', 'Is it common in gardens?', 'Is it rare?', 'Is it endangered?',
    'Does it eat seeds?', 'Does it eat fish?', 'Does it eat insects?', 'Does it eat fruit?', 'Does it eat nectar?',
    'Does it build a nest?', 'Does it lay eggs?', 'Is it black?', 'Is it white?', 'Is it yellow?',
    'Is it blue?', 'Is it red?', 'Is it black and white?', 'Is it a parrot?', 'Is it a falcon?',
    'Is it nocturnal?', 'Is it a water bird?', 'Is it a songbird?', 'Is it native to Europe?', 'Is it native to the tropics?',
    'Is it bigger than a pigeon?', 'Is it smaller than a robin?', 'Does it have a long neck?', 'Does it swim?', 'Is it a fast flyer?',
  ],
  Insects: [
    'Can it fly?', 'Is it very small?', 'Does it have wings?', 'Does it have six legs?', 'Does it have eight legs?',
    'Does it have antennae?', 'Does it have a sting?', 'Does it bite?', 'Is it dangerous?', 'Is it venomous?',
    'Is it colourful?', 'Is it black?', 'Is it yellow?', 'Is it brown?', 'Is it green?',
    'Does it live in colonies?', 'Does it live alone?', 'Does it make honey?', 'Does it spin a web?', 'Does it build a nest?',
    'Is it nocturnal?', 'Is it active during the day?', 'Does it crawl?', 'Does it jump?', 'Does it hop?',
    'Does it have a hard shell?', 'Does it have stripes?', 'Does it have spots?', 'Does it eat plants?', 'Does it eat other insects?',
    'Is it considered a pest?', 'Is it a pest in gardens?', 'Is it helpful to humans?', 'Is it a pollinator?', 'Does it live underground?',
    'Does it live in trees?', 'Does it live in water?', 'Does it make a loud noise?', 'Does it buzz?', 'Does it chirp?',
    'Is it a beetle?', 'Is it a bee or wasp?', 'Is it a butterfly or moth?', 'Is it a fly?', 'Is it an ant?',
    'Does it glow?', 'Is it attracted to light?', 'Does it live less than a year?', 'Can it lift many times its weight?', 'Is it a mosquito?',
  ],
  Dinosaurs: [
    'Is it a carnivore?', 'Is it a herbivore?', 'Is it bigger than a bus?', 'Is it taller than a house?', 'Is it smaller than a human?',
    'Could it fly?', 'Could it swim?', 'Did it walk on two legs?', 'Did it walk on four legs?', 'Did it have horns?',
    'Did it have spikes?', 'Did it have plates on its back?', 'Did it have a long neck?', 'Did it have a long tail?', 'Did it have sharp teeth?',
    'Did it have a crest?', 'Did it have a beak?', 'Did it have feathers?', 'Did it have scales?', 'Did it have claws?',
    'Did it live in the Jurassic?', 'Did it live in the Cretaceous?', 'Did it live in the Triassic?', 'Is it famous with kids?', 'Does it appear in Jurassic Park?',
    'Is it a T. rex relative?', 'Is it a sauropod?', 'Is it a predator?', 'Was it slow?', 'Was it fast?',
    'Is it one of the biggest dinosaurs?', 'Is it one of the smallest?', 'Could it roar in movies?', 'Did it live in herds?', 'Did it defend itself with its tail?',
    'Did it have a club tail?', 'Did it have a horn on its head?', 'Is its name hard to pronounce?', 'Does it start with T?', 'Is it a plant-eater?',
    'Does it have a brain the size of a walnut?', 'Is it a meat-eater?', 'Is it a famous movie dinosaur?', 'Is it in preschool shows?', 'Is it a raptor?',
  ],

  // ── People: real ──────────────────────────────────────────────────────
  Actors: [
    'Is the actor male?', 'Is the actor female?', 'Is the actor American?', 'Is the actor British?', 'Is the actor still alive?',
    'Is the actor over 50?', 'Is the actor under 40?', 'Has the actor won an Oscar?', 'Has the actor won multiple Oscars?', 'Is the actor known for action films?',
    'Is the actor known for comedies?', 'Is the actor known for dramas?', 'Is the actor known for horror?', 'Is the actor known for sci-fi?', 'Is the actor known for romance?',
    'Is the actor also a director?', 'Is the actor also a producer?', 'Is the actor also a musician?', 'Is the actor a comedian?', 'Is the actor tall?',
    'Has the actor been in the MCU?', 'Has the actor been in Star Wars?', 'Has the actor been Batman?', 'Has the actor been James Bond?', 'Is the actor European?',
    'Is the actor Australian?', 'Is the actor Canadian?', 'Is the actor blonde?', 'Is the actor dark-haired?', 'Does the actor often have a beard?',
    'Was the actor famous before 2000?', 'Was the actor famous in the 80s?', 'Was the actor famous in the 90s?', 'Is the actor active today?', 'Is the actor very famous worldwide?',
    'Is the actor mainly a movie star?', 'Is the actor on British TV?', 'Has the actor played a real person?', 'Has the actor played a villain?', 'Has the actor played a superhero?',
    'Has the actor played a historical figure?', 'Is the actor also known on stage?', 'Has the actor hosted SNL?', 'Is the actor in a big franchise?', 'Has the actor worked with Nolan?',
    'Has the actor worked with Spielberg?', 'Has the actor worked with Tarantino?', 'Has the actor worked with Scorsese?', 'Is the actor known for one iconic role?', 'Is the actor a method actor?',
  ],
  Celebrities: [
    'Is it a man?', 'Is it a woman?', 'Is the celebrity American?', 'Is the celebrity British?', 'Is the celebrity still alive?',
    'Is the celebrity over 40?', 'Is the celebrity under 30?', 'Is the celebrity known for music?', 'Is the celebrity known for acting?', 'Is the celebrity known for reality TV?',
    'Is the celebrity known for sport?', 'Is the celebrity known for being rich?', 'Is the celebrity known for social media?', 'Is the celebrity a singer?', 'Is the celebrity a comedian?',
    'Is the celebrity tall?', 'Does the celebrity have children?', 'Does the celebrity have famous siblings?', 'Has the celebrity been in a scandal?', 'Is the celebrity married to another celebrity?',
    'Is the celebrity blonde?', 'Is the celebrity dark-haired?', 'Does the celebrity have a beard?', 'Is the celebrity a YouTuber too?', 'Is the celebrity an entrepreneur?',
    'Has the celebrity won a Grammy?', 'Has the celebrity won an Oscar?', 'Is the celebrity famous worldwide?', 'Is the celebrity active on Instagram?', 'Is the celebrity known for modelling?',
    'Is the celebrity British?', 'Is the celebrity from Europe?', 'Is the celebrity very rich?', 'Is the celebrity controversial?', 'Was the celebrity famous as a child?',
    'Is the celebrity mainly TV-famous?', 'Is the celebrity in a famous family?', 'Does the celebrity have their own brand?', 'Is the celebrity a rapper?', 'Is the celebrity an athlete?',
    'Is the celebrity a footballer?', 'Is the celebrity a tennis player?', 'Is the celebrity a boxer?', 'Is the celebrity in a famous couple?', 'Is the celebrity often in the news?',
    'Is the celebrity older than 50?', 'Is the celebrity retired?', 'Has the celebrity been in movies?', 'Is the celebrity a pop star?', 'Is the celebrity an influencer?',
  ],
  'Football Players': [
    'Is the player still active?', 'Is the player a forward?', 'Is the player a midfielder?', 'Is the player a defender?', 'Is the player a goalkeeper?',
    'Is the player Brazilian?', 'Is the player Portuguese?', 'Is the player Argentinian?', 'Is the player French?', 'Is the player African?',
    'Is the player English?', 'Is the player Spanish?', 'Is the player Dutch?', 'Is the player Belgian?', 'Is the player German?',
    'Has the player won the World Cup?', 'Has the player won the Ballon d\'Or?', 'Has the player won multiple Ballons d\'Or?', 'Does the player play for a Spanish club?', 'Does the player play for an English club?',
    'Does the player play for an Italian club?', 'Does the player play for a German club?', 'Does the player play for a French club?', 'Has the player played for Real Madrid?', 'Has the player played for Barcelona?',
    'Has the player played for Manchester United?', 'Has the player played for Liverpool?', 'Has the player played for Bayern Munich?', 'Has the player played for PSG?', 'Has the player played for Chelsea?',
    'Is the player under 25?', 'Is the player over 30?', 'Is the player over 35?', 'Is the player a captain?', 'Does the player wear the number 10?',
    'Does the player wear the number 7?', 'Is the player known for dribbling?', 'Is the player known for scoring?', 'Is the player known for tackling?', 'Is the player known for free kicks?',
    'Is the player known for long shots?', 'Is the player known for headers?', 'Is the player left-footed?', 'Is the player right-footed?', 'Is the player very fast?',
    'Has the player been transferred for a huge fee?', 'Is the player African?', 'Is the player from South America?', 'Is the player one of the GOATs?', 'Does the player have a famous hair style?',
  ],
  'Music Artists': [
    'Is the artist solo?', 'Is the artist a man?', 'Is the artist a woman?', 'Is the artist American?', 'Is the artist British?',
    'Is the artist a pop artist?', 'Is the artist a rock artist?', 'Is the artist a rapper?', 'Is the artist an R&B artist?', 'Is the artist a DJ?',
    'Is the artist a country artist?', 'Is the artist a K-pop artist?', 'Is the artist in a band?', 'Does the artist play guitar?', 'Does the artist play piano?',
    'Is the artist still active?', 'Is the artist under 30?', 'Is the artist over 40?', 'Is the artist over 60?', 'Has the artist won a Grammy?',
    'Has the artist won multiple Grammys?', 'Is the artist famous worldwide?', 'Was the artist famous in the 2000s?', 'Was the artist famous in the 90s?', 'Was the artist famous before 1990?',
    'Did the artist headline Glastonbury?', 'Has the artist performed at the Super Bowl?', 'Is the artist from the UK?', 'Is the artist from Canada?', 'Is the artist European?',
    'Is the artist a singer-songwriter?', 'Does the artist write their own songs?', 'Is the artist a rapper from the US?', 'Has the artist been in a boy band?', 'Has the artist been in a girl group?',
    'Is the artist on Spotify\'s most-streamed?', 'Does the artist have a number 1 hit?', 'Has the artist changed genre over time?', 'Is the artist known for dancing?', 'Is the artist controversial?',
    'Is the artist a producer?', 'Does the artist collaborate with rappers?', 'Is the artist a rock legend?', 'Is the artist blonde?', 'Is the artist known for a distinctive voice?',
    'Has the artist released an album in the 2020s?', 'Is the artist a metal artist?', 'Is the artist Latin?',
  ],
  YouTubers: [
    'Does the YouTuber do gaming content?', 'Does the YouTuber do vlogs?', 'Does the YouTuber do comedy sketches?', 'Does the YouTuber do challenges?', 'Does the YouTuber do educational content?',
    'Is the YouTuber American?', 'Is the YouTuber British?', 'Is the YouTuber from another country?', 'Is the YouTuber a man?', 'Is the YouTuber a woman?',
    'Does the YouTuber have over 100 million subscribers?', 'Does the YouTuber have over 50 million subscribers?', 'Does the YouTuber have over 10 million subscribers?', 'Does the YouTuber mainly speak English?', 'Does the YouTuber make music too?',
    'Does the YouTuber stream on Twitch too?', 'Does the YouTuber do reaction videos?', 'Does the YouTuber do pranks?', 'Is the YouTuber part of a creator group?', 'Is the YouTuber known for unboxing?',
    'Is the YouTuber known for cars?', 'Is the YouTuber known for giveaways?', 'Is the YouTuber controversial?', 'Is the YouTuber also in mainstream media?', 'Has the YouTuber been in a boxing match?',
    'Does the YouTuber do storytelling videos?', 'Does the YouTuber animate?', 'Is the YouTuber younger than 30?', 'Is the YouTuber older than 40?', 'Does the YouTuber have a podcast?',
    'Does the YouTuber focus on Minecraft?', 'Does the YouTuber focus on Roblox?', 'Does the YouTuber focus on Fortnite?', 'Does the YouTuber have a brand?', 'Does the YouTuber sell merch?',
    'Is the YouTuber a family-friendly channel?', 'Is the YouTuber Spanish-speaking?', 'Is the YouTuber Indian?', 'Is the YouTuber known for charity?', 'Does the YouTuber do commentary?',
    'Is the YouTuber a couple channel?', 'Is the YouTuber known for food content?', 'Is the YouTuber known for travel?', 'Is the YouTuber known for fitness?', 'Is the YouTuber verified?',
    'Does the YouTuber collaborate with MrBeast?', 'Is the YouTuber on TikTok too?', 'Does the YouTuber earn from sponsorships?', 'Is the YouTuber famous worldwide?', 'Does the YouTuber reveal their face?',
  ],

  // ── People: characters ─────────────────────────────────────────────────
  'Movie Characters': [
    'Is the character a man?', 'Is the character a woman?', 'Is the character human?', 'Is the character an animal?', 'Is the character animated?',
    'Is the character a villain?', 'Is the character a hero?', 'Is the character a superhero?', 'Is the character from Disney?', 'Is the character from Pixar?',
    'Is the character from the MCU?', 'Is the character from DC?', 'Is the character from Star Wars?', 'Is the character from Harry Potter?', 'Is the character from a 90s film?',
    'Is the character from a horror film?', 'Is the character from a comedy?', 'Is the character from an action film?', 'Is the character from a children\'s film?', 'Is the character from a 2000s film?',
    'Is the character from a recent film?', 'Is the character blonde?', 'Is the character dark-haired?', 'Is the character bald?', 'Does the character wear a hat?',
    'Does the character wear a mask?', 'Does the character wear glasses?', 'Does the character use magic?', 'Does the character use a weapon?', 'Does the character have superpowers?',
    'Does the character fly?', 'Does the character have a sidekick?', 'Is the character royalty?', 'Is the character a teacher or mentor?', 'Is the character the protagonist?',
    'Does the character die in their film?', 'Is the character inspired by a book?', 'Is the character from a franchise?', 'Does the character have an iconic catchphrase?', 'Does the character wear a costume?',
    'Is the character funny?', 'Is the character sinister?', 'Is the character British?', 'Is the character American?', 'Is the character from before 2000?',
    'Does the character appear in TV too?', 'Is the character mythical?', 'Does the character have a famous look?', 'Does the character have a beard?', 'Is the character a kid?',
  ],
  'Disney Characters': [
    'Is the character a princess?', 'Is the character a man?', 'Is the character a woman?', 'Is the character human?', 'Is the character an animal?',
    'Is the character a villain?', 'Is the character a sidekick?', 'Is the character from a classic film?', 'Is the character from a modern film?', 'Is the character from a Pixar film?',
    'Is the character from the live-action remake?', 'Is the character royalty?', 'Is the character a queen?', 'Is the character a king?', 'Is the character a witch?',
    'Does the character sing?', 'Does the character have a sidekick?', 'Does the character have a famous song?', 'Is the character blonde?', 'Is the character dark-haired?',
    'Is the character an animal sidekick?', 'Is the character a fish?', 'Is the character a lion?', 'Is the character a mouse-classic?', 'Is the character from Frozen?',
    'Is the character from the Little Mermaid?', 'Is the character from Beauty and the Beast?', 'Is the character from Aladdin?', 'Is the character from Tangled?', 'Is the character from Moana?',
    'Is the character from Mulan?', 'Is the character from Snow White?', 'Is the character from Cinderella?', 'Is the character from Sleeping Beauty?', 'Is the character from Toy Story?',
    'Is the character from the Lion King?', 'Is the character from Wreck-It Ralph?', 'Is the character from Lilo & Stitch?', 'Is the character a villain in a film?', 'Is the character magical?',
    'Does the character have an animal companion?', 'Is the character from an animated series?', 'Is the character a Disney Princess brand member?', 'Does the character have a horse?', 'Is the character funny?',
    'Does the character have supernatural powers?', 'Is the character from a holiday special?', 'Is the character Mickey\'s friend?', 'Is the character from Winnie the Pooh?',
  ],
  'Marvel/DC Heroes': [
    'Is it a Marvel hero?', 'Is it a DC hero?', 'Is the hero male?', 'Is the hero female?', 'Is the hero a human?',
    'Is the hero an alien?', 'Does the hero have superpowers?', 'Is the hero a genius?', 'Is the hero rich?', 'Does the hero wear a suit of armour?',
    'Does the hero use a weapon?', 'Does the hero fly?', 'Does the hero have super strength?', 'Can the hero shoot lasers/energy?', 'Is the hero part of the Avengers?',
    'Is the hero part of the Justice League?', 'Is the hero a mutant?', 'Is the hero from New York?', 'Is the hero American?', 'Is the hero a god?',
    'Is the hero royalty?', 'Is the hero a scientist?', 'Is the hero trained as a soldier?', 'Is the hero a spy?', 'Is the hero a teenager?',
    'Is the hero associated with a colour?', 'Does the hero wear a cape?', 'Does the hero wear a mask?', 'Does the hero have a shield?', 'Does the hero use a hammer?',
    'Does the hero use a lasso?', 'Does the hero shoot webs?', 'Does the hero have claws?', 'Is the hero a founding Avenger?', 'Is the hero associated with bats?',
    'Is the hero associated with spiders?', 'Is the hero associated with a bow?', 'Is the hero associated with lightning?', 'Does the hero have a sidekick?', 'Has the hero been in a movie?',
    'Has the hero been in a big movie franchise?', 'Is the hero in the MCU?', 'Is the hero from Gotham?', 'Is the hero from Metropolis?', 'Does the hero turn into a monster?',
    'Is the hero green?', 'Is the hero a villain turned hero?', 'Does the hero have a movie solo?',
  ],
  'Marvel/DC Villains': [
    'Is it a Marvel villain?', 'Is it a DC villain?', 'Is the villain male?', 'Is the villain female?', 'Is the villain human?',
    'Is the villain an alien?', 'Is the villain a monster?', 'Is the villain a genius?', 'Is the villain rich?', 'Is the villain a crime boss?',
    'Is the villain a scientist?', 'Is the villain a warlord?', 'Is the villain a god?', 'Is the villain a mutant?', 'Is the villain magical?',
    'Does the villain have superpowers?', 'Does the villain fly?', 'Is the villain associated with the Fantastic Four?', 'Is the villain associated with Spider-Man?', 'Is the villain associated with Batman?',
    'Is the villain associated with Superman?', 'Is the villain associated with the X-Men?', 'Is the villain associated with the Avengers?', 'Is the villain associated with the Justice League?', 'Does the villain wear a mask?',
    'Does the villain wear a cape?', 'Is the villain green?', 'Is the villain bald?', 'Is the villain associated with a colour?', 'Does the villain use a weapon?',
    'Does the villain lead an army?', 'Is the villain a leader?', 'Is the villain a fanatic?', 'Has the villain appeared in movies?', 'Has the villain appeared in the MCU?',
    'Is the villain a Disney+ character?', 'Is the villain a boss in a movie?', 'Is the villain from space?', 'Is the villain an experiment?', 'Is the villain a trickster?',
    'Is the villain cold-themed?', 'Is the villain associated with lightning?', 'Is the villain scary?', 'Is the villain funny?', 'Is the villain charming?',
    'Is the villain associated with venom?', 'Does the villain wear a suit?', 'Is the villain a billionaire?', 'Does the villain have a plan to take over the world?', 'Is the villain iconic in comics?',
  ],
  'Harry Potter Characters': [
    'Is the character a student?', 'Is the character a teacher?', 'Is the character a wizard?', 'Is the character a witch?', 'Is the character from Gryffindor?',
    'Is the character from Slytherin?', 'Is the character from Ravenclaw?', 'Is the character from Hufflepuff?', 'Is the character a Death Eater?', 'Is the character a member of the Order?',
    'Is the character male?', 'Is the character female?', 'Is the character a Weasley?', 'Is the character a professor at Hogwarts?', 'Is the character the headmaster?',
    'Is the character a Hogwarts founder?', 'Is the character a ghost?', 'Is the character a muggle?', 'Is the character half-blood?', 'Is the character pure-blood?',
    'Is the character an Animagus?', 'Is the character a werewolf?', 'Does the character teach Potions?', 'Does the character teach Defence Against the Dark Arts?', 'Does the character teach Transfiguration?',
    'Is the character Harry\'s friend?', 'Is the character Harry\'s enemy?', 'Is the character close to Voldemort?', 'Is the character a Side character?', 'Does the character appear in every book?',
    'Is the character in the trio?', 'Is the character a Quidditch player?', 'Is the character a prefect?', 'Does the character own an owl, cat or toad?', 'Does the character speak Parseltongue?',
    'Is the character blonde?', 'Is the character dark-haired?', 'Is the character young?', 'Is the character old?', 'Is the character a Death Eater?',
    'Is the character a Ministry official?', 'Does the character appear in the films?', 'Is the character played by a famous actor?', 'Is the character a parent of Harry\'s friend?', 'Is the character a Malfoy?',
    'Does the character have a famous quote?', 'Is the character in Dumbledore\'s Army?', 'Does the character die?', 'Is the character loyal to Dumbledore?',
  ],
  'Star Wars Characters': [
    'Is the character a Jedi?', 'Is the character a Sith?', 'Is the character a droid?', 'Is the character an alien?', 'Is the character human?',
    'Is the character a man?', 'Is the character a woman?', 'Is the character a rebel?', 'Is the character an imperial?', 'Is the character from the original trilogy?',
    'Is the character from the prequel trilogy?', 'Is the character from the sequel trilogy?', 'Is the character from the shows?', 'Is the character a bounty hunter?', 'Is the character a smuggler?',
    'Is the character a senator?', 'Is the character a general?', 'Is the character a pilot?', 'Is the character a Stormtrooper?', 'Is the character a Wookiee?',
    'Is the character a cyborg?', 'Is the character old?', 'Is the character young?', 'Is the character a Jedi Master?', 'Is the character a Jedi Padawan?',
    'Does the character use a lightsaber?', 'Is the character\'s lightsaber green?', 'Is the character\'s lightsaber red?', 'Is the character\'s lightsaber blue?', 'Does the character use the Force?',
    'Is the character a Skywalker?', 'Is the character a Sith Lord?', 'Is the character a bounty hunter?', 'Does the character own a droid?', 'Is the character from Tatooine?',
    'Is the character a Mandalorian?', 'Is the character a famous movie villain?', 'Is the character a robot?', 'Is the character tall?', 'Is the character small?',
    'Does the character wear a mask?', 'Does the character wear a helmet?', 'Does the character wear a hood?', 'Is the character a hero?', 'Is the character a villain?',
    'Does the character appear in many films?', 'Is the character played by a famous actor?', 'Is the character a clone?', 'Is the character associated with the Resistance?', 'Is the character in the Clone Wars show?',
  ],

  // ── Places ─────────────────────────────────────────────────────────────
  'European Countries': [
    'Is the country in the EU?', 'Is the country in the Eurozone?', 'Does the country use the euro?', 'Is the country in Western Europe?', 'Is the country in Eastern Europe?',
    'Is the country in Northern Europe?', 'Is the country in Southern Europe?', 'Is the country in the Balkans?', 'Is the country in Scandinavia?', 'Is the country landlocked?',
    'Does the country border the Atlantic?', 'Does the country border the Mediterranean?', 'Does the country border Germany?', 'Does the country border France?', 'Is the country an island?',
    'Is the country a monarchy?', 'Is the country a republic?', 'Is the country big?', 'Is the country small?', 'Is the population under 10 million?',
    'Is the population over 30 million?', 'Does the country have mountains?', 'Does the country have famous beaches?', 'Is the country mountainous?', 'Is the country known for wine?',
    'Is the country known for beer?', 'Is the country known for cheese?', 'Is the country famous for football?', 'Has the country won the World Cup?', 'Is the country a former Soviet state?',
    'Is the country a former Yugoslav country?', 'Does the country have a royal family?', 'Is the country known for cold winters?', 'Is the country known for warm weather?', 'Is the country in central Europe?',
    'Does the country have a famous capital?', 'Is the country capital also the biggest city?', 'Is the country home to famous artists?', 'Is the country known for design?', 'Is the country known for cars?',
    'Is the country known for chocolate?', 'Does the country speak a Slavic language?', 'Does the country speak a Germanic language?', 'Does the country speak a Romance language?', 'Is the country in the Schengen area?',
    'Is the country neutral?', 'Is the country known for fjords?', 'Is the country known for tulips?', 'Is the country known for pasta?',
  ],
  'Countries': [
    'Is the country in Europe?', 'Is the country in Asia?', 'Is the country in Africa?', 'Is the country in North America?', 'Is the country in South America?',
    'Is the country in Oceania?', 'Is the country a big country?', 'Is the country small?', 'Is the country made up of islands?', 'Is the country landlocked?',
    'Is the country in the Northern Hemisphere?', 'Is the country in the Southern Hemisphere?', 'Is the country a famous tourist destination?', 'Is the country very hot?', 'Is the country very cold?',
    'Is the country a monarchy?', 'Is the country a republic?', 'Is the country a democracy?', 'Does the country use the euro?', 'Is the country part of the EU?',
    'Does the country have a famous capital city?', 'Does the country have famous beaches?', 'Does the country have mountains?', 'Does the country have deserts?', 'Does the country have a huge population?',
    'Is the country known for football?', 'Has the country won the World Cup?', 'Is the country known for food?', 'Is the country famous for history?', 'Is the country an island nation?',
    'Is the country home to famous landmarks?', 'Does the country have jungles?', 'Does the country have famous rivers?', 'Does the country have a large coastline?', 'Is the country known for cars?',
    'Is the country known for technology?', 'Is the country known for fashion?', 'Is the country English-speaking?', 'Is the country Spanish-speaking?', 'Is the country French-speaking?',
    'Is the country Portuguese-speaking?', 'Is the country in the Americas?', 'Does the country border the Atlantic?', 'Does the country border the Pacific?', 'Is the country in the Southern Hemisphere?',
    'Does the country have a famous royal family?', 'Is the country known for sake or wine?', 'Is the country known for a famous cuisine?', 'Is the country densely populated?',
  ],
  'European Cities': [
    'Is it a capital city?', 'Is the city in Western Europe?', 'Is the city in Eastern Europe?', 'Is the city in Northern Europe?', 'Is the city in Southern Europe?',
    'Is the city in Germany?', 'Is the city in France?', 'Is the city in Italy?', 'Is the city in Spain?', 'Is the city in the UK?',
    'Is the city in the Netherlands?', 'Is the city in Poland?', 'Is the city large?', 'Is the city small?', 'Is the city on the coast?',
    'Is the city famous for canals?', 'Is the city famous for museums?', 'Is the city home to a famous football club?', 'Is the city a popular tourist destination?', 'Is the city known for fashion?',
    'Is the city known for food?', 'Is the city known for art?', 'Is the city known for music?', 'Is the city known for beer?', 'Is the city known for wine?',
    'Does the city have a famous cathedral?', 'Does the city have a famous bridge?', 'Does the city have a famous palace?', 'Does the city have a famous tower?', 'Does the city have snow in winter?',
    'Is the city in the EU?', 'Is the city in Scandinavia?', 'Is the city in the Balkans?', 'Is the city in a monarchy?', 'Is the city in a former Soviet country?',
    'Is the city famous for a river?', 'Is the city famous for a beach?', 'Is the city famous for a castle?', 'Is the city famous for a university?', 'Is the city famous for an airport?',
    'Is the city in Austria or Switzerland?', 'Is the city in Eastern Europe?', 'Does the city have a metro?', 'Is the city known for being expensive?', 'Is the city famous for a festival?',
    'Is the city a port city?', 'Is the city in a Germanic-speaking country?',
  ],
  'World Capitals': [
    'Is the capital in Europe?', 'Is the capital in Asia?', 'Is the capital in Africa?', 'Is the capital in the Americas?', 'Is the capital in Oceania?',
    'Is the capital a large city?', 'Is the capital small?', 'Is the capital on the coast?', 'Is the capital inland?', 'Is the capital in a landlocked country?',
    'Is the capital in the Northern Hemisphere?', 'Is the capital in the Southern Hemisphere?', 'Is the capital very hot in summer?', 'Is the capital cold in winter?', 'Is the capital famous for landmarks?',
    'Does the capital have a famous monument?', 'Is the capital famous for museums?', 'Is the capital known for its food?', 'Is the capital known for fashion?', 'Is the capital a tourist destination?',
    'Is the capital in a famous football country?', 'Is the capital in the EU?', 'Is the capital in Asia?', 'Is the capital in a Spanish-speaking country?', 'Is the capital in a French-speaking country?',
    'Is the capital in a country that uses the euro?', 'Is the capital in a monarchy?', 'Is the capital in a republic?', 'Is the capital in North America?', 'Is the capital in South America?',
    'Did the capital host the Olympics?', 'Is the capital home to a famous square?', 'Is the capital home to a famous tower?', 'Is the capital home to a famous cathedral?', 'Is the capital known for a palace?',
    'Is the capital in a tropical country?', 'Is the capital in a desert country?', 'Is the capital densely populated?', 'Is the capital known for nightlife?', 'Is the capital on a river?',
    'Is the capital famous for a bridge?', 'Is the capital in an island country?', 'Is the capital in a mountain country?', 'Does the capital have a metro?', 'Is the capital old?',
    'Is the capital at a high altitude?', 'Is the capital the largest city in its country?',
  ],
  'Natural Wonders': [
    'Is it in Europe?', 'Is it in Asia?', 'Is it in Africa?', 'Is it in North America?', 'Is it in South America?',
    'Is it in Oceania?', 'Is it in the Northern Hemisphere?', 'Is it a mountain?', 'Is it a volcano?', 'Is it a waterfall?',
    'Is it a desert?', 'Is it a lake or sea?', 'Is it in or under the ocean?', 'Is it a forest or jungle?', 'Is it a canyon or valley?',
    'Is it an island or group of islands?', 'Is it made of rock?', 'Is it made of sand?', 'Is it made of ice or salt?', 'Does it involve water?',
    'Can you swim there?', 'Can you climb it?', 'Can you hike there?', 'Is it usually cold there?', 'Is it usually hot there?',
    'Does it snow there?', 'Is it at high altitude?', 'Is it below sea level?', 'Is it famous for its colors?', 'Is it bigger than a city?',
    'Is it one of the biggest of its kind on Earth?', 'Is it a UNESCO World Heritage site?', 'Is it inside a national park?', 'Do famous animals live there?', 'Is it dangerous to visit?',
    'Has it ever erupted?', 'Is it still growing or changing?', 'Is it millions of years old?', 'Is it near a big city?', 'Is it easy to visit as a tourist?',
    'Do many tourists visit it every year?', 'Is it surrounded by jungle?', 'Is it in a country where English is spoken?', 'Is it in a tropical place?', 'Can you take a boat there?',
    'Can you see it from an airplane?', 'Is it taller than it is wide?', 'Is it on a coastline?', 'Would you need special gear to explore it?', 'Is it famous from documentaries?',
  ],
  'Famous Landmarks': [
    'Is the landmark in Europe?', 'Is the landmark in Asia?', 'Is the landmark in Africa?', 'Is the landmark in the Americas?', 'Is the landmark man-made?',
    'Is the landmark natural?', 'Is the landmark a building?', 'Is the landmark a statue?', 'Is the landmark a tower?', 'Is the landmark a monument?',
    'Is the landmark an ancient ruin?', 'Is the landmark modern?', 'Is the landmark more than 500 years old?', 'Is the landmark more than 2000 years old?', 'Is the landmark built in the last 100 years?',
    'Is the landmark a UNESCO World Heritage Site?', 'Is the landmark in France?', 'Is the landmark in Italy?', 'Is the landmark in Egypt?', 'Is the landmark in the USA?',
    'Is the landmark in South America?', 'Is the landmark in Asia?', 'Is the landmark associated with a religion?', 'Is the landmark a castle?', 'Is the landmark a cathedral?',
    'Is the landmark a museum?', 'Is the landmark a bridge?', 'Is the landmark a sculpture?', 'Is the landmark in a capital city?', 'Is the landmark very tall?',
    'Is the landmark very heavy for its size?', 'Does the landmark have stairs?', 'Can you climb the landmark?', 'Is the landmark on a famous hill?', 'Is the landmark near water?',
    'Is the landmark in the desert?', 'Is the landmark in the mountains?', 'Is the landmark famous worldwide?', 'Is the landmark a symbol of its country?', 'Is the landmark one of the Seven Wonders?',
    'Is the landmark famous in photos?', 'Do tourists climb or visit inside?', 'Is the landmark associated with a famous artist?', 'Is the landmark famous at sunrise?', 'Is the landmark in a famous city?',
    'Is the landmark associated with a movie?', 'Does the landmark light up at night?',
  ],
  'US States': [
    'Is the state on the West Coast?', 'Is the state on the East Coast?', 'Is the state in the South?', 'Is the state in the Midwest?', 'Is the state in the Northeast?',
    'Is the state in the Mountain region?', 'Is the state in the Southwest?', 'Is the state landlocked?', 'Does the state border the Pacific?', 'Does the state border the Atlantic?',
    'Does the state border the Gulf of Mexico?', 'Does the state border Mexico?', 'Does the state border Canada?', 'Is the state very big in area?', 'Is the state small in area?',
    'Is the state very populated?', 'Is the state sparsely populated?', 'Is the state famous for beaches?', 'Is the state famous for mountains?', 'Is the state famous for deserts?',
    'Is the state famous for a national park?', 'Is the state known for Hollywood?', 'Is the state known for casinos?', 'Is the state known for country music?', 'Is the state known for tech?',
    'Is the state known for potatoes?', 'Is the state known for oranges?', 'Is the state known for corn?', 'Is the state known for oil?', 'Is the state known for auto industry?',
    'Is the state hot year-round?', 'Is the state cold in winter?', 'Is the state a southern state?', 'Is the state a northern state?', 'Is the state named after a person?',
    'Does the state have a famous city?', 'Is the state a battleground in elections?', 'Is the state historically Native American territory?', 'Is the state home to Disney World?', 'Is the state home to the Grand Canyon?',
    'Is the state home to Yellowstone?', 'Is the state home to Las Vegas?', 'Is the state home to Chicago?', 'Is the state one of the original 13 colonies?', 'Is the state in two time zones?',
    'Is the state a famous vacation state?',
  ],

  // ── Brands ──────────────────────────────────────────────────────────────
  'Fashion Brands': [
    'Is the brand luxury?', 'Is the brand Italian?', 'Is the brand French?', 'Is the brand American?', 'Is the brand European?',
    'Is the brand mainly clothing?', 'Is the brand mainly accessories/handbags?', 'Is the brand mainly shoes?', 'Is the brand mainly watches/jewellery?', 'Is the brand known for perfume?',
    'Is the brand over 100 years old?', 'Is the brand a newer brand?', 'Is the brand associated with a famous designer?', 'Is the brand known for streetwear?', 'Is the brand known for high fashion?',
    'Is the brand on the Paris Fashion Week runway?', 'Is the brand known for a signature logo?', 'Is the brand owned by a big conglomerate?', 'Is the brand mass-market?', 'Is the brand expensive?',
    'Is the brand known for denim/jeans?', 'Is the brand known for suits?', 'Is the brand known for sportswear-style?', 'Is the brand known for a monogram pattern?', 'Is the brand part of LVMH?',
    'Is the brand part of Kering?', 'Is the brand a household name?', 'Has the brand had controversy?', 'Is the brand affordable for most people?', 'Is the brand known for leather goods?',
    'Does the brand sell sunglasses?', 'Is the brand a sportswear brand too?', 'Is the brand British?', 'Is the brand German?', 'Is the brand Japanese?',
    'Does the brand have a US founder?', 'Is the brand associated with a celebrity?', 'Does the brand have a runway show?', 'Is the brand known for a red-soled shoe?', 'Is the brand iconic for handbags?',
    'Is the brand famous for trench coats?', 'Is the brand known for cashmere?', 'Is the brand known for knitwear?', 'Is the brand known for casual basics?', 'Is the brand known for elegance?',
    'Is the brand a sports sponsor?'
  ],
  'Tech Brands': [
    'Is the brand a hardware company?', 'Is the brand a software company?', 'Is the brand a social media company?', 'Is the brand a streaming service?', 'Is the brand a phone maker?',
    'Is the brand American?', 'Is the brand Asian?', 'Is the brand European?', 'Is the brand very famous?', 'Is the brand one of the trillion-dollar companies?',
    'Does the brand make smartphones?', 'Does the brand make laptops?', 'Does the brand make game consoles?', 'Does the brand make cars?', 'Is the brand mainly online services?',
    'Is the brand known for a search engine?', 'Is the brand known for a social network?', 'Is the brand known for an OS?', 'Is the brand known for a browser?', 'Is the brand known for cloud services?',
    'Is the brand known for AI?', 'Is the brand known for graphics cards?', 'Is the brand known for chips?', 'Is the brand known for a phone?', 'Does the brand have a famous founder?',
    'Is the brand founded by Steve Jobs era folk?', 'Is the brand older than 30 years?', 'Is the brand under 20 years old?', 'Does the brand make TVs?', 'Does the brand have its own app store?',
    'Is the brand associated with electric vehicles?', 'Is the brand a chipmaker?', 'Does the brand make wearables?', 'Is the brand a Chinese company?', 'Is the brand a Japanese company?',
    'Is the brand a Korean company?', 'Is the brand known for shopping?', 'Is the brand known for streaming movies?', 'Is the brand known for streaming games?', 'Is the brand known for an app?',
    'Is the brand on the stock market?', 'Is the brand headquartered in California?', 'Is the brand known for a famous logo?', 'Does the brand sell AI assistants?', 'Is the brand controversial?',
    'Is the brand known for video games?'
  ],
  'Fast Food Chains': [
    'Is the chain American?', 'Is the chain known for burgers?', 'Is the chain known for chicken?', 'Is the chain known for pizza?', 'Is the chain known for fries?',
    'Is the chain known for breakfast?', 'Is the chain known for coffee?', 'Is the chain known for ice cream?', 'Is the chain known for tacos?', 'Is the chain known for sandwiches?',
    'Is the chain worldwide?', 'Is the chain mainly in the USA?', 'Is the chain mainly takeout?', 'Is the chain mainly sit-down?', 'Is the chain known for a clown mascot?',
    'Is the chain known for a king mascot?', 'Is the chain known for a colonel?', 'Is the chain known for delivery?', 'Is the chain known for a value menu?', 'Is the chain cheap?',
    'Is the chain known for kids\' meals?', 'Is the chain known for a happy meal?', 'Is the chain known for nuggets?', 'Is the chain known for a Big Mac?', 'Does the chain have a famous arch logo?',
    'Is the chain known for a square patty?', 'Is the chain known for Italian food?', 'Is the chain known for a drive-thru?', 'Is the chain known for milkshakes?', 'Has the chain appeared in movies?',
    'Does the chain have a famous jingle?', 'Does the chain sell hot dogs?', 'Is the chain known for a flame-grilled burger?', 'Is the chain owned by a bigger company?', 'Is the chain known for cinnamon rolls?',
    'Is the chain known for donuts?', 'Is the chain known for a sausage sandwich?', 'Is the chain mostly in California?', 'Is the chain known for a secret menu?', 'Is the chain controversial?',
    'Is the chain famous for a kids\' mascot?', 'Does the chain have a famous color in its logo?', 'Is the chain east-coast American?', 'Is the chain known for curly fries?', 'Is the chain known for roast beef?',
    'Is the chain known for being open late?'
  ],
  'Sports Brands': [
    'Is the brand known for football kits?', 'Is the brand known for running shoes?', 'Is the brand known for basketball shoes?', 'Is the brand known for sneakers?', 'Is the brand American?',
    'Is the brand German?', 'Is the brand European?', 'Is the brand known for a famous athlete?', 'Does the brand make footballs?', 'Does the brand have the swoosh?',
    'Does the brand have three stripes?', 'Is the brand expensive?', 'Is the brand mass-market?', 'Is the brand known for athleisure?', 'Is the brand known for golf?',
    'Is the brand known for tennis?', 'Is the brand known for football/soccer?', 'Is the brand known for cycling?', 'Is the brand known for a famous logo?', 'Is the brand a sponsor of major events?',
    'Is the brand associated with Michael Jordan?', 'Is the brand associated with Cristiano Ronaldo?', 'Is the brand associated with Lionel Messi?', 'Does the brand make skateboarding shoes?', 'Does the brand make football boots?',
    'Is the brand known for hoodies?', 'Is the brand known for shorts?', 'Is the brand known for jerseys?', 'Is the brand older than 50 years?', 'Is the brand newer than 20 years?',
    'Is the brand known for a classic silhouette like a Stan Smith?', 'Is the brand known for slides?', 'Is the brand a lifestyle brand too?', 'Is the brand British?', 'Is the brand Japanese?',
    'Does the brand sponsor a famous club?', 'Is the brand on the stock market?', 'Is the brand known for a famous campaign?', 'Is the brand known for high performance?', 'Is the brand in FIFA?',
    'Is the brand a premium running brand?', 'Is the brand known for surf?', 'Is the brand known for snowboarding?',
  ],
  'Game Studios': [
    'Is the studio American?', 'Is the studio Japanese?', 'Is the studio European?', 'Is the studio known for RPGs?', 'Is the studio known for FPS games?',
    'Is the studio known for sports games?', 'Is the studio known for racing games?', 'Is the studio known for platformers?', 'Is the studio known for open-world games?', 'Is the studio known for horror games?',
    'Is the studio known for a famous franchise?', 'Is the studio owned by a major publisher?', 'Is the studio independent?', 'Is the studio known for fighting games?', 'Is the studio known for MMOs?',
    'Is the studio known for a sandbox game?', 'Is the studio known for a battle royale?', 'Is the studio known for a famous mascot?', 'Is the studio known for Mario?', 'Is the studio known for Sonic?',
    'Is the studio known for a famous shooter?', 'Is the studio known for a popular open world?', 'Is the studio known for episodic games?', 'Is the studio a AAA studio?', 'Is the studio a small indie studio?',
    'Is the studio known for a long-running series?', 'Is the studio known for a movie tie-in game?', 'Is the studio known for retro games?', 'Is the studio known for mobile games?', 'Is the studio based in California?',
    'Is the studio based in Japan?', 'Is the studio owned by Microsoft?', 'Is the studio owned by Sony?', 'Is the studio famous for PC games?', 'Is the studio known for its writing?',
    'Is the studio owned by EA?', 'Is the studio owned by Take-Two?', 'Is the studio known for a sports league license?', 'Is the studio known for a sandbox phenomenon?', 'Is the studio known for Grand Theft Auto?',
    'Is the studio known for Pokémon?', 'Is the studio known for Final Fantasy?', 'Is the studio known for The Sims?', 'Is the studio known for FIFA or EA FC?', 'Is the studio known for a famous universe?',
  ],
  'Car Brands': [
    'Is the brand German?', 'Is the brand American?', 'Is the brand Japanese?', 'Is the brand Italian?', 'Is the brand British?',
    'Is the brand Korean?', 'Is the brand French?', 'Is the brand Swedish?', 'Is the brand a luxury brand?', 'Is the brand mass-market?',
    'Does the brand make electric cars?', 'Does the brand make sports cars?', 'Does the brand make SUVs?', 'Does the brand make trucks?', 'Does the brand make supercars?',
    'Is the brand known for reliability?', 'Is the brand known for fast cars?', 'Is the brand known for off-road vehicles?', 'Is the brand known for affordable cars?', 'Is the brand known for a famous logo?',
    'Is the brand known for a leather interior?', 'Is the brand associated with racing?', 'Is the brand associated with Formula 1?', 'Is the brand a family-car brand?', 'Is the brand expensive?',
    'Does the brand make a famous sports car?', 'Is the brand known for a small city car?', 'Is the brand owned by a bigger group?', 'Is the brand a Chinese brand?', 'Is the brand known for a CUV?',
    'Does the brand make hybrids?', 'Is the brand over 100 years old?', 'Is the brand newer than 20 years?', 'Is the brand associated with a country?', 'Is the brand known for minivans?',
    'Does the brand have a famous model line?', 'Is the brand known for luxury sedans?', 'Is the brand known for a 4x4?', 'Is the brand known for hypercars?', 'Is the brand known for fuel efficiency?',
    'Is the brand known for an iconic design?', 'Is the brand known for SUVs and sedans?', 'Is the brand associated with a famous racing team?', 'Is the brand part of a famous group?',
  ],

  // ── Media ────────────────────────────────────────────────────────────────
  Movies: [
    'Is the movie animated?', 'Is it a Pixar film?', 'Is the movie a Disney film?', 'Is the movie a Marvel film?', 'Is the movie a DC film?',
    'Is the movie made by Disney?', 'Is the movie live-action?', 'Is the movie a sequel?', 'Is the movie a remake?', 'Is the movie a comedy?',
    'Is the movie a drama?', 'Is the movie an action film?', 'Is the movie a horror film?', 'Is the movie a sci-fi film?', 'Is the movie a romance?',
    'Is the movie a thriller?', 'Is the movie a fantasy?', 'Is the movie a musical?', 'Is the movie a documentary?', 'Is the movie family-friendly?',
    'Was the movie released before 2000?', 'Was the movie released in the 2000s?', 'Was the movie released in the 2010s?', 'Was the movie released in the 2020s?', 'Did the movie win an Oscar?',
    'Did the movie win Best Picture?', 'Does the movie have a famous director?', 'Is the movie by Pixar or Disney?', 'Is the movie by Christopher Nolan?', 'Is the movie by Spielberg?',
    'Is the movie by Tarantino?', 'Is the movie by Scorsese?', 'Is the movie long (over 2.5 hours)?', 'Is the movie short (under 90 min)?', 'Does the movie star Leonardo DiCaprio?',
    'Does the movie star Tom Hanks?', 'Does the movie star Meryl Streep?', 'Is the movie based on a book?', 'Is the movie based on real events?', 'Is the movie a superhero film?',
    'Does the movie have a famous soundtrack?', 'Is the movie in the MCU?', 'Is the movie a Disney classic?', 'Is the movie set in space?', 'Is the movie set in a school?',
    'Is the movie violent?', 'Is the movie funny?', 'Is it in black and white?', 'Is it a global blockbuster?', 'Is the movie well-known to kids?',
  ],
  'TV Shows': [
    'Is the show animated?', 'Is the show American?', 'Is the show British?', 'Is the show a sitcom?', 'Is the show a drama?',
    'Is the show a crime drama?', 'Is the show a sci-fi show?', 'Is the show a fantasy?', 'Is the show a reality show?', 'Is the show a documentary series?',
    'Is the show on Netflix?', 'Is the show on Disney+?', 'Is the show on HBO?', 'Is the show still running?', 'Has the show ended?',
    'Is the show from the 90s?', 'Is the show from the 2000s?', 'Is the show from after 2010?', 'Is the show a Netflix Original?', 'Is the show longer than 5 seasons?',
    'Is the show longer than 10 seasons?', 'Is the show a long-running cartoon?', 'Is the show an animated sitcom?', 'Is the show famous for a theme song?', 'Is the show famous for catchphrases?',
    'Does the show have a famous cast?', 'Has the show won Emmys?', 'Is the show very popular?', 'Is the show a crime procedural?', 'Is the show family-friendly?',
    'Is the show for adults only?', 'Is the show a superhero show?', 'Is the show a teen show?', 'Is the show a hospital drama?', 'Is the show a legal drama?',
    'Is the show animated on Adult Swim?', 'Is the show a sci-fi classic?', 'Is the show a fantasy hit?', 'Is the show based on a book?', 'Is the show a cooking show?',
    'Is the show about families?', 'Is the show famous for a wedding or finale?', 'Is the show satirical?', 'Is the show a talk show?', 'Is the show a game show?',
    'Is the show a long-running satire?', 'Is the show a spin-off?', 'Is the show a BBC hit?'
  ],
  'Video Games': [
    'Is the game a first-person shooter?', 'Is the game an RPG?', 'Is the game a strategy game?', 'Is the game a sports game?', 'Is the game a racing game?',
    'Is the game a platformer?', 'Is the game a sandbox game?', 'Is the game a fighting game?', 'Is the game a battle royale?', 'Is the game an MMO?',
    'Is the game made by Nintendo?', 'Is the game from a famous Japanese studio?', 'Is the game from a famous Western studio?', 'Is the game from Rockstar?', 'Is the game published by EA?',
    'Is the game released before 2000?', 'Is the game from the 2000s?', 'Is the game from the 2010s?', 'Is the game from the 2020s?', 'Does the game have a famous mascot?',
    'Does the game have a sequel?', 'Is the game part of a long franchise?', 'Is the game multiplayer?', 'Is the game mainly single-player?', 'Is the game on consoles?',
    'Is the game on PC?', 'Is the game on mobile?', 'Is the game a lowest-violence kids game?', 'Is the game Minecraft?', 'Is the game a Zelda game?',
    'Is the game a Mario game?', 'Is the game a Pokémon game?', 'Is the game GTA?', 'Is the game an FPS franchise?', 'Is the game a fighting legend?',
    'Is the game famous among speedrunners?', 'Is the game a subscription MMO?', 'Is the game a battle royale hit?', 'Is the game a simulation?', 'Is the game violent?',
    'Is the game a horror game?', 'Is the game known for its story?', 'Is the game known for art style?', 'Is the game enormously popular?', 'Is the game controversial?',
    'Is the game easy to learn?'
  ],
  Pokémon: [
    'Is the Pokémon a fire type?', 'Is the Pokémon a water type?', 'Is the Pokémon a grass type?', 'Is the Pokémon an electric type?', 'Is the Pokémon a psychic type?',
    'Is the Pokémon a flying type?', 'Is the Pokémon a rock type?', 'Is the Pokémon a ground type?', 'Is the Pokémon a ice type?', 'Is the Pokémon a poison type?',
    'Is the Pokémon a ghost type?', 'Is the Pokémon a dragon type?', 'Is the Pokémon a dark type?', 'Is the Pokémon a fairy type?', 'Is the Pokémon a bug type?',
    'Is the Pokémon a steel type?', 'Is the Pokémon a fighting type?', 'Is the Pokémon normal type?', 'Is the Pokémon legendary?', 'Is the Pokémon a mythical?',
    'Is the Pokémon from Gen 1?', 'Is the Pokémon from Gen 2?', 'Is the Pokémon from Gen 3?', 'Is the Pokémon from a later gen?', 'Is the Pokémon a starter?',
    'Is the Pokémon small?', 'Is the Pokémon big?', 'Is the Pokémon a flyless classic?', 'Can the Pokémon fly?', 'Can the Pokémon swim?',
    'Does the Pokémon evolve?', 'Does the Pokémon have a mega evolution?', 'Is the Pokémon very famous?', 'Is the Pokémon cute?', 'Is the Pokémon a fan favourite?',
    'Is the Pokémon a Pikachu-like?', 'Is the Pokémon blue?', 'Is the Pokémon yellow?', 'Is the Pokémon red?', 'Is the Pokémon green?',
    'Is the mascot of Pokémon just Pikachu?', 'Is the Pokémon a biped?', 'Is the Pokémon quadruped?', 'Does the Pokémon have horns?', 'Does the Pokémon have a tail?',
    'Is the Pokémon in Smash Bros?', 'Does the Pokémon appear early in the Pokédex?'
  ],

  // ── Objects ────────────────────────────────────────────────────────────
  // ── Food Pack ───────────────────────────────────────────────────────────
  Fruits: [
    'Does it grow on a tree?', 'Does it grow on a bush?', 'Does it grow on a vine?', 'Is it tropical?', 'Is it a citrus fruit?',
    'Is it a berry?', 'Does it have a peel you remove?', 'Does it have edible skin?', 'Does it have seeds?', 'Does it have a pit or stone?',
    'Is it usually yellow?', 'Is it usually red?', 'Is it usually green?', 'Is it usually orange?', 'Is it usually purple?',
    'Is it juicy?', 'Is it sour?', 'Is it sweet?', 'Is it crunchy?', 'Is it soft?',
    'Can you eat it in one bite?', 'Do you need to cut it?', 'Is it bigger than a fist?', 'Is it smaller than a golf ball?', 'Does it grow in a bunch?',
    'Is it often used in smoothies?', 'Is it often used in desserts?', 'Is it often dried?', 'Is it often juiced?', 'Is it a common lunchbox fruit?',
    'Does it have fuzzy skin?', 'Does it have a spiky exterior?', 'Is it mostly water?', 'Is it high in vitamin C?', 'Does it ripen after picking?',
    'Is it native to warm climates?', 'Is it eaten whole, skin and all?', 'Does it have a strong smell?', 'Is it often paired with cheese?', 'Is it a summer fruit?',
    'Is it used to make jam?', 'Does it float in water?', 'Is it commonly sliced onto cereal?', 'Is it a stone fruit?', 'Does it have segments inside?',
    'Is it green on the outside and different inside?', 'Is it often eaten as a snack?', 'Does it grow in clusters?', 'Is it used in fruit salad?', 'Is it a popular kids\' fruit?',
  ],
  Vegetables: [
    'Does it grow underground?', 'Does it grow above ground?', 'Is it a root vegetable?', 'Is it a leafy green?', 'Does it grow on a vine?',
    'Is it usually green?', 'Is it usually orange?', 'Is it usually white?', 'Is it usually red?', 'Is it usually purple?',
    'Can you eat it raw?', 'Is it usually cooked before eating?', 'Is it crunchy?', 'Is it soft when cooked?', 'Does it have a strong smell?',
    'Does it have layers?', 'Does it have a thick skin?', 'Is it bitter?', 'Is it starchy?', 'Is it watery?',
    'Is it often used in salads?', 'Is it often used in soup?', 'Is it often roasted?', 'Is it often boiled?', 'Is it often fried?',
    'Does it have seeds inside?', 'Does it grow in a pod?', 'Is it a type of squash?', 'Is it in the onion family?', 'Is it in the cabbage family?',
    'Is it a common pizza topping?', 'Is it a common salad ingredient?', 'Do kids usually dislike it?', 'Is it high in fiber?', 'Is it low in calories?',
    'Does it need to be peeled?', 'Is it bigger than a fist?', 'Is it smaller than a golf ball?', 'Does it have a stalk?', 'Is it often paired with dip?',
    'Is it used to make fries or chips?', 'Does it have a spicy variety?', 'Is it a common side dish?', 'Is it grown in a garden bed?', 'Does it have a strong flavor?',
    'Is it often stir-fried?', 'Is it a winter vegetable?', 'Is it a summer vegetable?', 'Does it have a crunchy texture raw?', 'Is it commonly grated?',
  ],
  'Snacks & Candy': [
    'Is it sweet?', 'Is it salty?', 'Is it sour?', 'Is it spicy?', 'Is it chocolate-based?',
    'Is it chewy?', 'Is it crunchy?', 'Is it sticky?', 'Does it melt in your mouth?', 'Does it come in a wrapper?',
    'Does it come in a bag?', 'Does it come in a box?', 'Is it fizzy or tingly?', 'Is it gummy?', 'Does it have a stick?',
    'Is it colorful?', 'Does it come in multiple flavors?', 'Is it a chip or crisp?', 'Is it a type of candy?', 'Is it a chocolate bar?',
    'Is it often eaten at the movies?', 'Is it often given out on Halloween?', 'Is it a childhood favorite?', 'Is it sold at checkout counters?', 'Does it have nuts in it?',
    'Does it have caramel in it?', 'Is it a hard candy?', 'Does it come on a lollipop stick?', 'Is it bite-sized?', 'Do you share it or eat it alone?',
    'Is it baked?', 'Is it fried?', 'Is it a brand-name snack?', 'Does it have a crunchy shell?', 'Is it messy to eat?',
    'Does it stain your fingers?', 'Is it a popular party snack?', 'Is it low in nutrition?', 'Is it often paired with a drink?', 'Does it have a mascot?',
    'Is it round?', 'Is it a bar shape?', 'Does it have a filling inside?', 'Is it a seasonal treat?', 'Would you find it in a vending machine?',
    'Is it popular with kids?', 'Is it popular at the cinema?', 'Does it require no preparation?', 'Is it a healthier snack option?', 'Does it come in a multipack?',
  ],
  Desserts: [
    'Is it baked?', 'Is it fried?', 'Is it frozen?', 'Is it served hot?', 'Is it served cold?',
    'Does it contain chocolate?', 'Does it contain fruit?', 'Does it have a crust?', 'Does it have layers?', 'Does it have frosting or icing?',
    'Is it a type of cake?', 'Is it a type of pie?', 'Is it a type of ice cream?', 'Is it a type of cookie?', 'Is it a type of pastry?',
    'Is it creamy?', 'Is it crunchy?', 'Is it gooey?', 'Is it fluffy?', 'Is it eaten with a spoon?',
    'Is it eaten with your hands?', 'Is it served in a bowl?', 'Is it served on a plate?', 'Is it a French dessert?', 'Is it an Italian dessert?',
    'Is it commonly eaten for breakfast?', 'Is it a birthday party treat?', 'Is it a holiday tradition?', 'Does it need to be refrigerated?', 'Does it have caramel in it?',
    'Does it have nuts in it?', 'Does it have cinnamon in it?', 'Is it drizzled with syrup or sauce?', 'Is it topped with whipped cream?', 'Is it a single-serving size?',
    'Would you share it with someone?', 'Is it a warm comfort food?', 'Is it made with eggs?', 'Is it made with milk or cream?', 'Does it have a crunchy topping?',
    'Is it typically round?', 'Is it typically rectangular?', 'Is it homemade more often than store-bought?', 'Is it a common wedding dessert?', 'Does it have multiple textures?',
    'Is it rich and heavy?', 'Is it light and airy?', 'Would it melt if left out?', 'Is it a classic diner dessert?', 'Does it pair well with coffee?',
  ],
  Drinks: [
    'Is it served hot?', 'Is it served cold?', 'Is it served over ice?', 'Is it fizzy?', 'Is it alcoholic?',
    'Does it contain caffeine?', 'Does it contain dairy?', 'Does it contain fruit?', 'Does it contain sugar?', 'Is it a hot beverage?',
    'Is it a soft drink?', 'Is it a type of tea?', 'Is it a type of coffee?', 'Is it a type of juice?', 'Is it a type of smoothie?',
    'Is it usually served in a mug?', 'Is it usually served in a glass?', 'Is it usually served in a can or bottle?', 'Does it have a straw?', 'Does it have foam on top?',
    'Is it sweet?', 'Is it bitter?', 'Is it sour?', 'Is it creamy?', 'Is it clear or transparent?',
    'Is it brown or dark colored?', 'Is it a bright color?', 'Is it commonly drunk at breakfast?', 'Is it commonly drunk at parties?', 'Is it a popular gym or workout drink?',
    'Does it help you wake up?', 'Does it help you relax?', 'Is it a common hangover cure?', 'Is it a kids\' drink?', 'Is it a summer drink?',
    'Is it a winter drink?', 'Is it made from a plant?', 'Is it made by fermentation?', 'Does it have a famous brand?', 'Is it often garnished with mint or fruit?',
    'Would you drink it at a café?', 'Would you drink it at a bar?', 'Is it a milk-based drink?', 'Is it a carbonated drink?', 'Does it need to be shaken or blended?',
    'Is it usually shared, like a pitcher?', 'Is it a single-serving drink?', 'Does it have a strong smell?', 'Is it a health drink?', 'Is it a treat, not an everyday drink?',
  ],
  'World Dishes': [
    'Is it spicy?', 'Is it savory?', 'Is it served hot?', 'Is it served cold?', 'Does it contain meat?',
    'Does it contain fish or seafood?', 'Is it vegetarian?', 'Does it contain rice?', 'Does it contain pasta or noodles?', 'Does it contain bread?',
    'Does it contain cheese?', 'Is it eaten with your hands?', 'Is it eaten with chopsticks?', 'Is it eaten with a fork and knife?', 'Is it wrapped or rolled?',
    'Is it a soup or has broth?', 'Is it fried?', 'Is it grilled?', 'Is it baked?', 'Is it raw?',
    'Is it from Asia?', 'Is it from Europe?', 'Is it from Latin America?', 'Is it from the Middle East?', 'Is it from Africa?',
    'Is it a breakfast dish?', 'Is it a street food?', 'Is it a fast food item?', 'Is it a comfort food?', 'Is it usually shared at the table?',
    'Is it a single-portion dish?', 'Does it have a sauce or dip?', 'Is it crunchy?', 'Is it saucy or wet?', 'Is it colorful?',
    'Is it a common takeout order?', 'Is it a well-known dish worldwide?', 'Would you eat it for lunch?', 'Would you eat it for dinner?', 'Is it a festival or holiday food?',
    'Does it come wrapped in dough or a wrapper?', 'Is it stuffed or filled with something?', 'Is it typically served on a plate?', 'Is it typically served in a bowl?', 'Does it need utensils to eat?',
    'Is it a popular restaurant dish?', 'Is it usually homemade?', 'Does it use a lot of spices?', 'Is it named after a place?', 'Would kids typically enjoy it?',
  ],

  'Household Objects': [
    'Is it found in the kitchen?', 'Is it found in the bathroom?', 'Is it found in the living room?', 'Is it found in the bedroom?', 'Is it found in the garage?',
    'Is it used every day?', 'Is it electronic?', 'Does it use electricity?', 'Does it use batteries?', 'Is it small?',
    'Is it large?', 'Can you hold it in one hand?', 'Is it made of metal?', 'Is it made of plastic?', 'Is it made of glass?',
    'Is it made of wood?', 'Is it made of fabric?', 'Is it sharp?', 'Is it hollow?', 'Can you cook with it?',
    'Can you clean with it?', 'Is it used for cleaning?', 'Can you sit on it?', 'Can you store things in it?', 'Do you eat with it?',
    'Does it have a screen?', 'Does it make noise?', 'Does it have a cord?', 'Is it heavy?', 'Is it light?',
    'Is it breakable?', 'Is it waterproof?', 'Is it usually white?', 'Is it usually metal?', 'Is it usually plastic?',
    'Does it have buttons?', 'Does it have a handle?', 'Does it have a lid?', 'Does it have a switch?', 'Do you wash it regularly?',
    'Is it part of a set?', 'Does it plug into a wall socket?', 'Does it use water?', 'Is it furniture?', 'Is it decorative?',
    'Is it a tool?', 'Would you pack it when moving houses?', 'Is it dangerous to children?'
  ],
};

// Fallback for categories without a specific bank.
export const UNIVERSAL_QUESTIONS = [
  'Is it small?', 'Is it large?', 'Is it heavy?', 'Is it famous?', 'Is it colourful?',
  'Is it man-made?', 'Is it natural?', 'Is it common?', 'Is it rare?', 'Is it expensive?',
  'Is it cheap?', 'Is it old?', 'Is it modern?', 'Is it still popular?', 'Does it have a name?',
  'Does it have a logo?', 'Is it found in everyday life?', 'Is it something kids know about?', 'Is it loud?', 'Is it quiet?',
  'Is it used by many people?', 'Is it a brand?', 'Is it a person?', 'Is it a place?', 'Is it a thing?',
];

// ~50 weird/funny questions that work for any category. Sent ~10% of the time
// by getRandomQuestion to add surprise and variety across a session.
export const FUNNY_QUESTIONS = [
  'Would it survive a zombie apocalypse?', 'Could a toddler reasonably fight it?', 'Is it afraid of the dark?',
  'Does it deserve a hug?', 'Has it ever been on TV?', 'Would your grandma use it?',
  'Is it more dramatic than your ex?', 'Does it gossip?', 'Could it spy on you?',
  'Would you marry it?', 'Could it steal your job?', 'Is it plotting something right now?',
  'Does it have trust issues?', 'Would it survive 5 seconds with a toddler?', 'Could it beat a hamster in a fight?',
  'Is it an introvert?', 'Does it need a therapist?', 'Could it win a rap battle?',
  'Would it ride shotgun in your car?', 'Does it smell weird?', 'Is it ashamed of itself?',
  'Has it ever lied to you?', 'Could you gift it to your in-laws?', 'Does it have unresolved trauma?',
  'Would it ghost you after one date?', 'Is it low-key iconic?', 'Does it have a secret identity?',
  'Could it survive being microwaved?', 'Would it win in a lawsuit against you?', 'Does it judge your fashion choices?',
  'Could you fit it in a backpack you stole?', 'Is it haunted?', 'Would a toddler cry if they saw it?',
  'Does it have main character energy?', 'Could it survive a group chat drama?', 'Is it scared of cats?',
  'Would it survive a week with your family?', 'Is it lowkey sus?', 'Does it think it\'s better than you?',
  'Could a raccoon steal it?', 'Is it emotionally available?', 'Would it pass a vibes check?',
  'Does it hide secrets?', 'Could it survive a flight with no legroom?', 'Is it the antagonist in its story?',
  'Would a goose honk at it aggressively?', 'Is it cooler than you?', 'Does it keep you up at night?',
  'Could it survive a TikTok trend?', 'Would you trust it with your WiFi password?'
];

// Returns a random question for the given category that isn't recently asked.
// ~10% of the time it pulls from FUNNY_QUESTIONS instead for surprise/wildcard variety.
export function getRandomQuestion(category, previousQuestions = []) {
  const used = new Set(previousQuestions.map(q => q.toLowerCase().trim()));
  // 10% chance → weird/funny wildcard bank (works for any category)
  if (Math.random() < 0.1) {
    const available = FUNNY_QUESTIONS.filter(q => !used.has(q.toLowerCase().trim()));
    const source = available.length > 0 ? available : FUNNY_QUESTIONS;
    return source[Math.floor(Math.random() * source.length)];
  }
  const pool = QUESTION_BANK_BY_CATEGORY[category] || UNIVERSAL_QUESTIONS;
  const available = pool.filter(q => !used.has(q.toLowerCase().trim()));
  const source = available.length > 0 ? available : pool;
  return source[Math.floor(Math.random() * source.length)];
}