// Practice-bot fact matrix — European Countries.
// Words: Germany, France, United Kingdom, Italy, Spain, Poland, Netherlands,
// Belgium, Sweden, Norway, Denmark, Finland, Switzerland, Austria, Portugal,
// Greece, Czech Republic, Romania, Hungary, Ireland, Croatia, Slovakia,
// Bulgaria, Ukraine, Iceland, Luxembourg, Slovenia, Serbia, Cyprus, Malta.
//
// Facts current as of early 2026 (EU/euro/Schengen membership, NATO after the
// Finland/Sweden accessions, Bulgaria's 2026 euro adoption, Romania/Bulgaria's
// 2025 full Schengen entry). Genuinely fuzzy cells (regional labels, "famous
// for X") are 'sometimes' — the bot commits one reading per game and never
// eliminates such a country from the player's answers.
// q(id, en, nl, yesList, someList, extra) — every country not listed is NO.
const q = (id, en, nl, yes, some = [], extra = false) => ({ id, en, nl, yes, some, extra });

const EU = ['Germany', 'France', 'Italy', 'Spain', 'Poland', 'Netherlands', 'Belgium', 'Sweden', 'Denmark',
  'Finland', 'Austria', 'Portugal', 'Greece', 'Czech Republic', 'Romania', 'Hungary', 'Ireland', 'Croatia',
  'Slovakia', 'Bulgaria', 'Luxembourg', 'Slovenia', 'Cyprus', 'Malta'];
const EURO = ['Germany', 'France', 'Italy', 'Spain', 'Netherlands', 'Belgium', 'Austria', 'Portugal',
  'Greece', 'Ireland', 'Finland', 'Slovakia', 'Slovenia', 'Luxembourg', 'Cyprus', 'Malta', 'Croatia', 'Bulgaria'];
const ALL = ['Germany', 'France', 'United Kingdom', 'Italy', 'Spain', 'Poland', 'Netherlands', 'Belgium',
  'Sweden', 'Norway', 'Denmark', 'Finland', 'Switzerland', 'Austria', 'Portugal', 'Greece', 'Czech Republic',
  'Romania', 'Hungary', 'Ireland', 'Croatia', 'Slovakia', 'Bulgaria', 'Ukraine', 'Iceland', 'Luxembourg',
  'Slovenia', 'Serbia', 'Cyprus', 'Malta'];

export default {
  category: 'European Countries',
  questions: [
  q('eu', 'Is the country in the EU?', 'Ligt het land in de EU?', EU),
  q('eurozone', 'Is the country in the Eurozone?', 'Ligt het land in de eurozone?', EURO),
  q('euro', 'Does the country use the euro?', 'Gebruikt het land de euro?', EURO),
  q('west', 'Is the country in Western Europe?', 'Ligt het land in West-Europa?',
    ['France', 'United Kingdom', 'Netherlands', 'Belgium', 'Ireland', 'Luxembourg'],
    ['Germany', 'Switzerland', 'Spain', 'Portugal']),
  q('east', 'Is the country in Eastern Europe?', 'Ligt het land in Oost-Europa?',
    ['Ukraine', 'Romania', 'Bulgaria'],
    ['Poland', 'Hungary', 'Slovakia', 'Czech Republic', 'Serbia', 'Croatia']),
  q('north', 'Is the country in Northern Europe?', 'Ligt het land in Noord-Europa?',
    ['Sweden', 'Norway', 'Denmark', 'Finland', 'Iceland'],
    ['United Kingdom', 'Ireland']),
  q('south', 'Is the country in Southern Europe?', 'Ligt het land in Zuid-Europa?',
    ['Italy', 'Spain', 'Portugal', 'Greece', 'Cyprus', 'Malta'],
    ['Croatia', 'Serbia']),
  q('balkans', 'Is the country in the Balkans?', 'Ligt het land op de Balkan?',
    ['Serbia', 'Bulgaria', 'Croatia'], ['Greece', 'Romania', 'Slovenia']),
  q('scandinavia', 'Is the country in Scandinavia?', 'Ligt het land in Scandinavië?',
    ['Sweden', 'Norway', 'Denmark'], ['Finland', 'Iceland']),
  q('landlocked', 'Is the country landlocked?', 'Is het land ingesloten door land?',
    ['Switzerland', 'Austria', 'Czech Republic', 'Slovakia', 'Hungary', 'Luxembourg', 'Serbia']),
  q('atlantic', 'Does the country border the Atlantic?', 'Grenst het land aan de Atlantische Oceaan?',
    ['France', 'Spain', 'Portugal', 'Ireland', 'United Kingdom', 'Iceland'],
    ['Norway', 'Netherlands', 'Belgium', 'Denmark', 'Germany']),
  q('mediterranean', 'Does the country border the Mediterranean?', 'Grenst het land aan de Middellandse Zee?',
    ['France', 'Spain', 'Italy', 'Greece', 'Croatia', 'Malta', 'Cyprus'], ['Slovenia']),
  q('bordersde', 'Does the country border Germany?', 'Grenst het land aan Duitsland?',
    ['France', 'Netherlands', 'Belgium', 'Luxembourg', 'Switzerland', 'Austria', 'Czech Republic', 'Poland', 'Denmark']),
  q('bordersfr', 'Does the country border France?', 'Grenst het land aan Frankrijk?',
    ['Germany', 'Belgium', 'Luxembourg', 'Switzerland', 'Italy', 'Spain']),
  q('island', 'Is the country an island?', 'Is het land een eiland?',
    ['Iceland', 'Ireland', 'Malta', 'Cyprus', 'United Kingdom']),
  q('monarchy', 'Is the country a monarchy?', 'Is het land een monarchie?',
    ['United Kingdom', 'Netherlands', 'Belgium', 'Sweden', 'Norway', 'Denmark', 'Spain', 'Luxembourg']),
  q('republic', 'Is the country a republic?', 'Is het land een republiek?',
    ['Germany', 'France', 'Italy', 'Poland', 'Finland', 'Switzerland', 'Austria', 'Portugal', 'Greece',
     'Czech Republic', 'Romania', 'Hungary', 'Ireland', 'Croatia', 'Slovakia', 'Bulgaria', 'Ukraine',
     'Iceland', 'Slovenia', 'Serbia', 'Cyprus', 'Malta']),
  q('big', 'Is the country big?', 'Is het land groot?',
    ['France', 'Spain', 'Sweden', 'Germany', 'Poland', 'Ukraine', 'Norway', 'Finland'],
    ['Italy', 'Romania', 'United Kingdom']),
  q('smallc', 'Is the country small?', 'Is het land klein?',
    ['Luxembourg', 'Malta', 'Cyprus', 'Slovenia'],
    ['Belgium', 'Netherlands', 'Switzerland', 'Denmark', 'Slovakia', 'Croatia', 'Ireland', 'Iceland']),
  q('popunder10', 'Is the population under 10 million?', 'Heeft het land minder dan 10 miljoen inwoners?',
    ['Norway', 'Denmark', 'Finland', 'Ireland', 'Croatia', 'Slovakia', 'Bulgaria', 'Iceland', 'Luxembourg',
     'Slovenia', 'Serbia', 'Cyprus', 'Malta', 'Switzerland', 'Austria', 'Hungary'],
    ['Sweden', 'Greece', 'Portugal', 'Czech Republic']),
  q('popover30', 'Is the population over 30 million?', 'Heeft het land meer dan 30 miljoen inwoners?',
    ['Germany', 'France', 'United Kingdom', 'Italy', 'Spain', 'Poland'], ['Ukraine']),
  q('mountains', 'Does the country have mountains?', 'Heeft het land bergen?',
    ['Switzerland', 'Austria', 'France', 'Italy', 'Spain', 'Germany', 'Norway', 'Poland', 'Slovakia',
     'Slovenia', 'Bulgaria', 'Romania', 'Greece', 'Serbia', 'Ukraine', 'Sweden', 'Iceland', 'Croatia', 'Czech Republic'],
    ['Portugal', 'United Kingdom', 'Ireland', 'Hungary', 'Cyprus', 'Finland', 'Belgium', 'Luxembourg']),
  q('beaches', 'Does the country have famous beaches?', 'Heeft het land beroemde stranden?',
    ['Spain', 'Portugal', 'Greece', 'Italy', 'France', 'Croatia', 'Cyprus', 'Malta'],
    ['Netherlands', 'Denmark', 'Bulgaria']),
  q('mountainous', 'Is the country mountainous?', 'Is het land bergachtig?',
    ['Switzerland', 'Austria', 'Norway', 'Slovenia', 'Greece', 'Iceland'],
    ['Italy', 'Spain', 'Bulgaria', 'Serbia', 'Slovakia', 'Romania', 'Croatia', 'Cyprus']),
  q('wine', 'Is the country known for wine?', 'Staat het land bekend om wijn?',
    ['France', 'Italy', 'Spain', 'Portugal'],
    ['Germany', 'Greece', 'Hungary', 'Austria', 'Croatia', 'Bulgaria', 'Romania', 'Slovenia', 'Switzerland']),
  q('beer', 'Is the country known for beer?', 'Staat het land bekend om bier?',
    ['Germany', 'Belgium', 'Czech Republic', 'Ireland', 'Netherlands'],
    ['United Kingdom', 'Austria', 'Poland', 'Denmark']),
  q('cheese', 'Is the country known for cheese?', 'Staat het land bekend om kaas?',
    ['France', 'Netherlands', 'Switzerland', 'Italy', 'Greece'], ['Denmark', 'United Kingdom']),
  q('football', 'Is the country famous for football?', 'Is het land beroemd om voetbal?',
    ['Germany', 'France', 'United Kingdom', 'Italy', 'Spain', 'Netherlands', 'Portugal', 'Croatia', 'Belgium'],
    ['Poland', 'Serbia', 'Sweden', 'Denmark', 'Greece', 'Ukraine', 'Czech Republic', 'Hungary']),
  q('worldcup', 'Has the country won the World Cup?', 'Heeft het land het WK gewonnen?',
    ['Germany', 'France', 'Italy', 'Spain', 'United Kingdom']),
  q('soviet', 'Is the country a former Soviet state?', 'Was het land een voormalige Sovjetstaat?',
    ['Ukraine']),
  q('yugoslav', 'Is the country a former Yugoslav country?', 'Was het land een voormalig Joegoslavisch land?',
    ['Croatia', 'Slovenia', 'Serbia']),
  q('royals', 'Does the country have a royal family?', 'Heeft het land een koninklijke familie?',
    ['United Kingdom', 'Netherlands', 'Belgium', 'Sweden', 'Norway', 'Denmark', 'Spain', 'Luxembourg']),
  q('coldwinters', 'Is the country known for cold winters?', 'Staat het land bekend om koude winters?',
    ['Norway', 'Sweden', 'Finland', 'Iceland', 'Ukraine', 'Poland'],
    ['Czech Republic', 'Austria', 'Switzerland', 'Romania', 'Slovakia', 'Hungary', 'Germany', 'Bulgaria', 'Serbia', 'Denmark']),
  q('warm', 'Is the country known for warm weather?', 'Staat het land bekend om warm weer?',
    ['Spain', 'Italy', 'Greece', 'Portugal', 'Cyprus', 'Malta'],
    ['France', 'Croatia', 'Bulgaria', 'Serbia']),
  q('central', 'Is the country in central Europe?', 'Ligt het land in Centraal-Europa?',
    ['Germany', 'Poland', 'Czech Republic', 'Slovakia', 'Hungary', 'Austria', 'Switzerland', 'Slovenia'],
    ['Croatia']),
  q('famouscapital', 'Does the country have a famous capital?', 'Heeft het land een beroemde hoofdstad?',
    ['France', 'United Kingdom', 'Italy', 'Spain', 'Germany', 'Netherlands', 'Austria', 'Greece',
     'Czech Republic', 'Hungary', 'Portugal', 'Ireland', 'Belgium', 'Denmark', 'Sweden'],
    ['Norway', 'Poland', 'Finland', 'Switzerland', 'Ukraine', 'Croatia', 'Romania', 'Serbia', 'Bulgaria',
     'Iceland', 'Slovakia', 'Slovenia', 'Cyprus', 'Malta', 'Luxembourg']),
  q('capbiggest', 'Is the country capital also the biggest city?', 'Is de hoofdstad ook de grootste stad?',
    ['Germany', 'France', 'United Kingdom', 'Italy', 'Spain', 'Poland', 'Netherlands', 'Sweden', 'Norway',
     'Denmark', 'Finland', 'Austria', 'Portugal', 'Greece', 'Czech Republic', 'Romania', 'Hungary',
     'Ireland', 'Croatia', 'Slovakia', 'Bulgaria', 'Ukraine', 'Iceland', 'Luxembourg', 'Slovenia',
     'Serbia', 'Cyprus'],
    ['Belgium']),
  q('artists', 'Is the country home to famous artists?', 'Komen er beroemde kunstenaars vandaan?',
    ['Italy', 'France', 'Netherlands', 'Spain'],
    ['Germany', 'United Kingdom', 'Austria', 'Norway', 'Greece', 'Belgium']),
  q('design', 'Is the country known for design?', 'Staat het land bekend om design?',
    ['Italy', 'Sweden', 'Denmark', 'Finland'],
    ['Netherlands', 'Germany', 'Switzerland', 'France']),
  q('cars', 'Is the country known for cars?', 'Staat het land bekend om auto’s?',
    ['Germany', 'Italy'],
    ['France', 'Sweden', 'United Kingdom', 'Czech Republic', 'Spain']),
  q('chocolate', 'Is the country known for chocolate?', 'Staat het land bekend om chocolade?',
    ['Switzerland', 'Belgium'], ['Germany', 'France', 'Netherlands']),
  q('slavic', 'Does the country speak a Slavic language?', 'Spreekt men er een Slavische taal?',
    ['Poland', 'Czech Republic', 'Slovakia', 'Croatia', 'Slovenia', 'Serbia', 'Bulgaria', 'Ukraine']),
  q('germanic', 'Does the country speak a Germanic language?', 'Spreekt men er een Germaanse taal?',
    ['Germany', 'United Kingdom', 'Netherlands', 'Austria', 'Switzerland', 'Sweden', 'Norway', 'Denmark',
     'Iceland', 'Luxembourg'],
    ['Belgium', 'Ireland']),
  q('romance', 'Does the country speak a Romance language?', 'Spreekt men er een Romaanse taal?',
    ['France', 'Italy', 'Spain', 'Portugal', 'Romania'],
    ['Switzerland', 'Belgium', 'Luxembourg']),
  q('schengen', 'Is the country in the Schengen area?', 'Ligt het land in het Schengengebied?',
    ['Germany', 'France', 'Italy', 'Spain', 'Poland', 'Netherlands', 'Belgium', 'Sweden', 'Norway',
     'Denmark', 'Finland', 'Switzerland', 'Austria', 'Portugal', 'Greece', 'Czech Republic', 'Hungary',
     'Croatia', 'Slovakia', 'Slovenia', 'Iceland', 'Luxembourg', 'Malta', 'Bulgaria', 'Romania'],
    ['Cyprus']),
  q('neutral', 'Is the country neutral?', 'Is het land neutraal?',
    ['Switzerland', 'Austria', 'Ireland'], ['Malta', 'Serbia', 'Cyprus']),
  q('fjords', 'Is the country known for fjords?', 'Staat het land bekend om fjorden?',
    ['Norway'], ['Iceland']),
  q('tulips', 'Is the country known for tulips?', 'Staat het land bekend om tulpen?',
    ['Netherlands']),
  q('pasta', 'Is the country known for pasta?', 'Staat het land bekend om pasta?',
    ['Italy']),

  // ── Answer-only extras: common free-text phrasings, honest by lookup ──────
  q('x_europe', 'Is the country in Europe?', 'Ligt het land in Europa?', ALL, [], true),
  q('x_place', 'Is it a place?', 'Is het een plek?', ALL, [], true),
  q('x_person', 'Is it a person?', 'Is het een persoon?', [], [], true),
  q('x_animal', 'Is it an animal?', 'Is het een dier?', [], [], true),
  q('x_thing', 'Is it a thing?', 'Is het een ding?', [], [], true),
  q('x_coast', 'Does the country have a coastline?', 'Heeft het land een kustlijn?',
    ['Germany', 'France', 'United Kingdom', 'Italy', 'Spain', 'Poland', 'Netherlands', 'Belgium', 'Sweden',
     'Norway', 'Denmark', 'Finland', 'Portugal', 'Greece', 'Romania', 'Ireland', 'Croatia', 'Bulgaria',
     'Ukraine', 'Iceland', 'Slovenia', 'Cyprus', 'Malta'], [], true),
  q('x_english', 'Do they speak English?', 'Spreekt men er Engels?',
    ['United Kingdom', 'Ireland', 'Malta'], ['Cyprus', 'Netherlands'], true),
  q('x_german', 'Do they speak German?', 'Spreekt men er Duits?',
    ['Germany', 'Austria', 'Switzerland'], ['Luxembourg', 'Belgium'], true),
  q('x_french', 'Do they speak French?', 'Spreekt men er Frans?',
    ['France'], ['Belgium', 'Switzerland', 'Luxembourg'], true),
  q('x_dutch', 'Do they speak Dutch?', 'Spreekt men er Nederlands?',
    ['Netherlands'], ['Belgium'], true),
  q('x_nato', 'Is the country in NATO?', 'Is het land lid van de NAVO?',
    ['Germany', 'France', 'United Kingdom', 'Italy', 'Spain', 'Poland', 'Netherlands', 'Belgium', 'Norway',
     'Denmark', 'Iceland', 'Portugal', 'Greece', 'Czech Republic', 'Romania', 'Hungary', 'Croatia',
     'Slovakia', 'Bulgaria', 'Slovenia', 'Luxembourg', 'Finland', 'Sweden'], [], true),
  q('x_ski', 'Is the country known for skiing?', 'Staat het land bekend om skiën?',
    ['Switzerland', 'Austria'],
    ['France', 'Italy', 'Norway', 'Sweden', 'Finland', 'Slovenia', 'Germany'], true),
  q('x_vikings', 'Is the country known for Vikings?', 'Staat het land bekend om Vikingen?',
    ['Norway', 'Denmark', 'Sweden'], ['Iceland'], true),
  q('x_tourist', 'Is the country a famous tourist destination?', 'Is het land een populaire toeristenbestemming?',
    ['France', 'Spain', 'Italy', 'Greece', 'Portugal', 'United Kingdom', 'Netherlands', 'Austria',
     'Switzerland', 'Croatia'],
    ['Germany', 'Ireland', 'Iceland', 'Czech Republic', 'Hungary', 'Cyprus', 'Malta', 'Norway', 'Sweden', 'Denmark', 'Poland'], true),
  q('x_russia', 'Does the country border Russia?', 'Grenst het land aan Rusland?',
    ['Finland', 'Poland', 'Norway', 'Ukraine'], [], true),
  q('x_islands', 'Does the country have many islands?', 'Heeft het land veel eilanden?',
    ['Greece', 'Croatia', 'Sweden', 'Finland', 'Norway'],
    ['Denmark', 'Italy', 'Spain', 'United Kingdom', 'Malta'], true),
  q('x_famousfood', 'Is the country known for its food?', 'Staat het land bekend om het eten?',
    ['Italy', 'France', 'Spain', 'Greece'],
    ['Portugal', 'Belgium', 'Germany', 'Hungary'], true),
  q('x_history', 'Is the country famous for its history?', 'Is het land beroemd om zijn geschiedenis?',
    ['Italy', 'Greece', 'France', 'United Kingdom', 'Germany', 'Spain'],
    ['Portugal', 'Austria', 'Hungary', 'Czech Republic', 'Ukraine', 'Serbia', 'Croatia', 'Cyprus', 'Ireland'], true),
  ],
};
