// Practice-bot fact matrix — Household Objects.
// q(id, en, nl, yesList, someList, extra) — every word not listed is NO.
// 'extra' rows are answer-only: they widen what free-text questions the bots
// can answer HONESTLY, but bots never ask them (they stick to the real bank).
const q = (id, en, nl, yes, some = [], extra = false) => ({ id, en, nl, yes, some, extra });

export default {
  category: 'Household Objects',
  questions: [
  q('kitchen', 'Is it found in the kitchen?', 'Vind je het in de keuken?',
    ['Refrigerator', 'Microwave', 'Oven', 'Knife', 'Mug', 'Kettle', 'Toaster', 'Coffee Machine'],
    ['Washing Machine', 'Table', 'Chair', 'Clock', 'Towel', 'Soap', 'Broom']),
  q('bathroom', 'Is it found in the bathroom?', 'Vind je het in de badkamer?',
    ['Toothbrush', 'Toilet', 'Shower', 'Towel', 'Soap', 'Mirror'],
    ['Washing Machine']),
  q('livingroom', 'Is it found in the living room?', 'Vind je het in de woonkamer?',
    ['Sofa', 'Television', 'Remote Control', 'Bookshelf', 'Lamp'],
    ['Table', 'Chair', 'Clock', 'Pillow', 'Mirror', 'Desk']),
  q('bedroom', 'Is it found in the bedroom?', 'Vind je het in de slaapkamer?',
    ['Bed', 'Wardrobe', 'Pillow'],
    ['Lamp', 'Mirror', 'Clock', 'Desk', 'Phone Charger', 'Television', 'Chair']),
  q('garage', 'Is it found in the garage?', 'Vind je het in de garage?',
    [],
    ['Broom', 'Washing Machine']),
  q('daily', 'Is it used every day?', 'Wordt het elke dag gebruikt?',
    ['Chair', 'Table', 'Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Television', 'Lamp', 'Mirror', 'Pillow',
     'Toothbrush', 'Toilet', 'Mug', 'Clock', 'Towel', 'Soap', 'Shower', 'Phone Charger', 'Remote Control'],
    ['Microwave', 'Oven', 'Knife', 'Kettle', 'Toaster', 'Coffee Machine', 'Desk', 'Bookshelf', 'Washing Machine']),
  q('electronic', 'Is it electronic?', 'Is het elektronisch?',
    ['Refrigerator', 'Microwave', 'Oven', 'Washing Machine', 'Television', 'Vacuum Cleaner', 'Kettle',
     'Toaster', 'Coffee Machine', 'Remote Control', 'Phone Charger'],
    ['Clock', 'Lamp']),
  q('electricity', 'Does it use electricity?', 'Gebruikt het elektriciteit?',
    ['Refrigerator', 'Microwave', 'Oven', 'Washing Machine', 'Television', 'Lamp', 'Vacuum Cleaner',
     'Kettle', 'Toaster', 'Coffee Machine', 'Remote Control', 'Clock', 'Phone Charger'],
    ['Toothbrush']),
  q('batteries', 'Does it use batteries?', 'Gebruikt het batterijen?',
    ['Remote Control'],
    ['Clock', 'Toothbrush', 'Vacuum Cleaner']),
  q('small', 'Is it small?', 'Is het klein?',
    ['Toothbrush', 'Knife', 'Mug', 'Remote Control', 'Soap', 'Phone Charger'],
    ['Clock', 'Lamp', 'Towel', 'Pillow', 'Kettle', 'Toaster']),
  q('large', 'Is it large?', 'Is het groot?',
    ['Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Washing Machine', 'Bookshelf'],
    ['Table', 'Television', 'Desk', 'Oven', 'Shower']),
  q('onehand', 'Can you hold it in one hand?', 'Kun je het met één hand vasthouden?',
    ['Toothbrush', 'Knife', 'Mug', 'Remote Control', 'Soap', 'Phone Charger'],
    ['Clock', 'Towel', 'Kettle', 'Lamp', 'Pillow']),
  q('metal', 'Is it made of metal?', 'Is het van metaal?',
    ['Knife', 'Kettle', 'Toaster', 'Refrigerator', 'Washing Machine', 'Oven', 'Microwave'],
    ['Lamp', 'Coffee Machine', 'Broom', 'Clock', 'Desk', 'Chair', 'Table', 'Bed']),
  q('plastic', 'Is it made of plastic?', 'Is het van plastic?',
    ['Remote Control', 'Phone Charger', 'Toothbrush'],
    ['Vacuum Cleaner', 'Coffee Machine', 'Kettle', 'Broom', 'Clock', 'Lamp', 'Chair']),
  q('glass', 'Is it made of glass?', 'Is het van glas?',
    ['Mirror'],
    ['Television', 'Lamp', 'Table', 'Oven', 'Mug', 'Coffee Machine']),
  q('wood', 'Is it made of wood?', 'Is het van hout?',
    ['Bookshelf', 'Wardrobe', 'Desk', 'Table'],
    ['Chair', 'Bed', 'Broom', 'Mirror']),
  q('fabric', 'Is it made of fabric?', 'Is het van stof?',
    ['Pillow', 'Towel', 'Sofa'],
    ['Bed', 'Chair']),
  q('sharp', 'Is it sharp?', 'Is het scherp?',
    ['Knife'],
    []),
  q('hollow', 'Is it hollow?', 'Is het hol?',
    ['Mug', 'Kettle'],
    ['Wardrobe', 'Refrigerator', 'Microwave', 'Oven', 'Washing Machine', 'Toilet', 'Toaster', 'Coffee Machine']),
  q('cook', 'Can you cook with it?', 'Kun je ermee koken?',
    ['Oven', 'Microwave'],
    ['Knife', 'Kettle', 'Toaster']),
  q('cleanwith', 'Can you clean with it?', 'Kun je ermee schoonmaken?',
    ['Vacuum Cleaner', 'Broom', 'Soap', 'Washing Machine'],
    ['Towel', 'Toothbrush', 'Shower']),
  q('forcleaning', 'Is it used for cleaning?', 'Wordt het gebruikt om schoon te maken?',
    ['Vacuum Cleaner', 'Broom', 'Soap', 'Washing Machine'],
    ['Towel', 'Toothbrush', 'Shower']),
  q('sit', 'Can you sit on it?', 'Kun je erop zitten?',
    ['Chair', 'Sofa', 'Bed', 'Toilet'],
    ['Table', 'Desk', 'Pillow']),
  q('store', 'Can you store things in it?', 'Kun je er spullen in bewaren?',
    ['Wardrobe', 'Refrigerator', 'Bookshelf'],
    ['Desk']),
  q('eatwith', 'Do you eat with it?', 'Eet je ermee?',
    ['Knife'],
    ['Mug', 'Table']),
  q('screen', 'Does it have a screen?', 'Heeft het een scherm?',
    ['Television'],
    ['Microwave', 'Oven', 'Washing Machine', 'Coffee Machine', 'Clock']),
  q('noise', 'Does it make noise?', 'Maakt het geluid?',
    ['Washing Machine', 'Vacuum Cleaner', 'Television', 'Kettle', 'Coffee Machine', 'Microwave'],
    ['Toaster', 'Clock', 'Refrigerator', 'Toilet', 'Shower', 'Oven']),
  q('cord', 'Does it have a cord?', 'Heeft het een snoer?',
    ['Lamp', 'Television', 'Refrigerator', 'Microwave', 'Oven', 'Washing Machine', 'Kettle', 'Toaster',
     'Coffee Machine', 'Phone Charger'],
    ['Vacuum Cleaner']),
  q('heavy', 'Is it heavy?', 'Is het zwaar?',
    ['Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Washing Machine', 'Bookshelf'],
    ['Table', 'Television', 'Desk', 'Oven', 'Vacuum Cleaner', 'Microwave', 'Toilet']),
  q('lightweight', 'Is it light?', 'Is het licht?',
    ['Toothbrush', 'Remote Control', 'Soap', 'Phone Charger', 'Towel', 'Pillow', 'Knife'],
    ['Mug', 'Broom', 'Clock', 'Lamp']),
  q('breakable', 'Is it breakable?', 'Is het breekbaar?',
    ['Mirror', 'Television', 'Lamp', 'Mug'],
    ['Clock', 'Toilet', 'Coffee Machine']),
  q('waterproof', 'Is it waterproof?', 'Is het waterdicht?',
    ['Toilet', 'Shower', 'Mug'],
    ['Washing Machine', 'Kettle']),
  q('white', 'Is it usually white?', 'Is het meestal wit?',
    ['Refrigerator', 'Washing Machine', 'Toilet'],
    ['Microwave', 'Oven', 'Pillow', 'Towel', 'Shower', 'Toothbrush', 'Soap']),
  q('usuallymetal', 'Is it usually metal?', 'Is het meestal van metaal?',
    ['Knife', 'Kettle', 'Toaster'],
    ['Refrigerator', 'Washing Machine', 'Oven', 'Microwave', 'Lamp']),
  q('usuallyplastic', 'Is it usually plastic?', 'Is het meestal van plastic?',
    ['Remote Control', 'Phone Charger', 'Toothbrush'],
    ['Vacuum Cleaner', 'Coffee Machine', 'Broom', 'Clock', 'Kettle']),
  q('buttons', 'Does it have buttons?', 'Heeft het knoppen?',
    ['Microwave', 'Washing Machine', 'Remote Control', 'Coffee Machine'],
    ['Television', 'Oven', 'Toaster', 'Vacuum Cleaner', 'Clock']),
  q('handle', 'Does it have a handle?', 'Heeft het een handvat?',
    ['Mug', 'Knife', 'Broom', 'Vacuum Cleaner', 'Kettle', 'Refrigerator', 'Oven'],
    ['Microwave', 'Wardrobe', 'Washing Machine', 'Toilet', 'Desk']),
  q('lid', 'Does it have a lid?', 'Heeft het een deksel?',
    ['Kettle', 'Toilet'],
    ['Coffee Machine', 'Washing Machine', 'Mug']),
  q('switch', 'Does it have a switch?', 'Heeft het een schakelaar?',
    ['Lamp', 'Kettle', 'Vacuum Cleaner'],
    ['Television', 'Toaster', 'Coffee Machine', 'Microwave', 'Oven', 'Washing Machine', 'Clock']),
  q('washreg', 'Do you wash it regularly?', 'Was je het regelmatig?',
    ['Mug', 'Knife', 'Towel'],
    ['Pillow', 'Toothbrush', 'Mirror', 'Toilet', 'Shower']),
  q('set', 'Is it part of a set?', 'Is het onderdeel van een set?',
    [],
    ['Chair', 'Knife', 'Mug', 'Towel', 'Pillow', 'Table']),
  q('socket', 'Does it plug into a wall socket?', 'Steek je het in een stopcontact?',
    ['Lamp', 'Television', 'Refrigerator', 'Microwave', 'Oven', 'Washing Machine', 'Vacuum Cleaner',
     'Kettle', 'Toaster', 'Coffee Machine', 'Phone Charger'],
    []),
  q('water', 'Does it use water?', 'Gebruikt het water?',
    ['Washing Machine', 'Toilet', 'Shower', 'Kettle', 'Coffee Machine'],
    ['Toothbrush', 'Soap', 'Towel', 'Mug']),
  q('furniture', 'Is it furniture?', 'Is het een meubelstuk?',
    ['Chair', 'Table', 'Sofa', 'Bed', 'Wardrobe', 'Bookshelf', 'Desk'],
    ['Mirror']),
  q('decorative', 'Is it decorative?', 'Is het decoratief?',
    [],
    ['Mirror', 'Lamp', 'Clock', 'Pillow', 'Bookshelf']),
  q('tool', 'Is it a tool?', 'Is het gereedschap?',
    ['Knife', 'Broom'],
    ['Vacuum Cleaner', 'Toothbrush']),
  q('moving', 'Would you pack it when moving houses?', 'Zou je het inpakken bij een verhuizing?',
    ['Chair', 'Table', 'Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Microwave', 'Washing Machine',
     'Television', 'Lamp', 'Mirror', 'Pillow', 'Toothbrush', 'Vacuum Cleaner', 'Knife', 'Mug', 'Kettle',
     'Toaster', 'Coffee Machine', 'Remote Control', 'Bookshelf', 'Desk', 'Clock', 'Towel', 'Soap',
     'Phone Charger', 'Broom'],
    ['Oven']),
  q('dangerous', 'Is it dangerous to children?', 'Is het gevaarlijk voor kinderen?',
    ['Knife'],
    ['Oven', 'Kettle', 'Toaster']),

  // ── Answer-only extras: common free-text phrasings, honest by lookup ──────
  q('x_alive', 'Is it alive?', 'Leeft het?', [], [], true),
  q('x_animal', 'Is it an animal?', 'Is het een dier?', [], [], true),
  q('x_person', 'Is it a person?', 'Is het een persoon?', [], [], true),
  q('x_place', 'Is it a place?', 'Is het een plek?', [], ['Shower', 'Toilet'], true),
  q('x_thing', 'Is it a thing?', 'Is het een ding?',
    ['Chair', 'Table', 'Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Microwave', 'Oven', 'Washing Machine',
     'Television', 'Lamp', 'Mirror', 'Pillow', 'Toothbrush', 'Toilet', 'Vacuum Cleaner', 'Knife', 'Mug',
     'Kettle', 'Toaster', 'Coffee Machine', 'Remote Control', 'Bookshelf', 'Desk', 'Clock', 'Towel',
     'Soap', 'Shower', 'Phone Charger', 'Broom'], [], true),
  q('x_eat', 'Can you eat it?', 'Kun je het eten?', [], [], true),
  q('x_food', 'Is it food?', 'Is het eten?', [], [], true),
  q('x_manmade', 'Is it man-made?', 'Is het door mensen gemaakt?',
    ['Chair', 'Table', 'Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Microwave', 'Oven', 'Washing Machine',
     'Television', 'Lamp', 'Mirror', 'Pillow', 'Toothbrush', 'Toilet', 'Vacuum Cleaner', 'Knife', 'Mug',
     'Kettle', 'Toaster', 'Coffee Machine', 'Remote Control', 'Bookshelf', 'Desk', 'Clock', 'Towel',
     'Soap', 'Shower', 'Phone Charger', 'Broom'], [], true),
  q('x_natural', 'Is it natural?', 'Is het natuurlijk?', [], [], true),
  q('x_soft', 'Is it soft?', 'Is het zacht?',
    ['Pillow', 'Towel'], ['Sofa', 'Bed'], true),
  q('x_round', 'Is it round?', 'Is het rond?',
    [], ['Clock', 'Mirror', 'Mug'], true),
  q('x_expensive', 'Is it expensive?', 'Is het duur?',
    ['Refrigerator', 'Washing Machine', 'Television', 'Sofa', 'Oven'],
    ['Bed', 'Coffee Machine', 'Wardrobe', 'Vacuum Cleaner', 'Microwave', 'Desk', 'Bookshelf', 'Table', 'Shower'], true),
  q('x_cheap', 'Is it cheap?', 'Is het goedkoop?',
    ['Soap', 'Toothbrush', 'Mug', 'Towel', 'Broom'],
    ['Knife', 'Pillow', 'Clock', 'Lamp', 'Phone Charger', 'Remote Control'], true),
  q('x_common', 'Is it common?', 'Is het gewoon?',
    ['Chair', 'Table', 'Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Microwave', 'Oven', 'Washing Machine',
     'Television', 'Lamp', 'Mirror', 'Pillow', 'Toothbrush', 'Toilet', 'Vacuum Cleaner', 'Knife', 'Mug',
     'Kettle', 'Toaster', 'Coffee Machine', 'Remote Control', 'Bookshelf', 'Desk', 'Clock', 'Towel',
     'Soap', 'Shower', 'Phone Charger', 'Broom'], [], true),
  q('x_rare', 'Is it rare?', 'Is het zeldzaam?', [], [], true),
  q('x_famous', 'Is it famous?', 'Is het beroemd?', [], [], true),
  q('x_brand', 'Is it a brand?', 'Is het een merk?', [], [], true),
  q('x_modern', 'Is it modern?', 'Is het modern?',
    ['Television', 'Microwave', 'Coffee Machine', 'Phone Charger', 'Remote Control', 'Washing Machine', 'Vacuum Cleaner'],
    ['Toaster', 'Kettle', 'Refrigerator', 'Lamp'], true),
  q('x_kids', 'Is it something kids know about?', 'Kennen kinderen het?',
    ['Chair', 'Table', 'Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Microwave', 'Oven', 'Washing Machine',
     'Television', 'Lamp', 'Mirror', 'Pillow', 'Toothbrush', 'Toilet', 'Vacuum Cleaner', 'Knife', 'Mug',
     'Kettle', 'Toaster', 'Coffee Machine', 'Remote Control', 'Bookshelf', 'Desk', 'Clock', 'Towel',
     'Soap', 'Shower', 'Phone Charger', 'Broom'], [], true),
  q('x_everyday', 'Is it found in everyday life?', 'Kom je het in het dagelijks leven tegen?',
    ['Chair', 'Table', 'Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Microwave', 'Oven', 'Washing Machine',
     'Television', 'Lamp', 'Mirror', 'Pillow', 'Toothbrush', 'Toilet', 'Vacuum Cleaner', 'Knife', 'Mug',
     'Kettle', 'Toaster', 'Coffee Machine', 'Remote Control', 'Bookshelf', 'Desk', 'Clock', 'Towel',
     'Soap', 'Shower', 'Phone Charger', 'Broom'], [], true),
  q('x_many', 'Is it used by many people?', 'Wordt het door veel mensen gebruikt?',
    ['Chair', 'Table', 'Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Microwave', 'Oven', 'Washing Machine',
     'Television', 'Lamp', 'Mirror', 'Pillow', 'Toothbrush', 'Toilet', 'Vacuum Cleaner', 'Knife', 'Mug',
     'Kettle', 'Toaster', 'Coffee Machine', 'Remote Control', 'Bookshelf', 'Desk', 'Clock', 'Towel',
     'Soap', 'Shower', 'Phone Charger', 'Broom'], [], true),
  q('x_loud', 'Is it loud?', 'Is het luid?',
    ['Vacuum Cleaner'], ['Washing Machine', 'Television', 'Kettle', 'Coffee Machine', 'Microwave'], true),
  q('x_colourful', 'Is it colourful?', 'Is het kleurrijk?',
    [], ['Towel', 'Pillow', 'Mug'], true),
  q('x_moving', 'Does it have moving parts?', 'Heeft het bewegende delen?',
    ['Washing Machine', 'Vacuum Cleaner', 'Clock', 'Toaster', 'Coffee Machine', 'Microwave'],
    ['Oven', 'Refrigerator', 'Kettle', 'Remote Control', 'Lamp'], true),
  q('x_wear', 'Can you wear it?', 'Kun je het dragen?', [], ['Towel'], true),
  q('x_shoebox', 'Is it bigger than a shoebox?', 'Is het groter dan een schoenendoos?',
    ['Chair', 'Table', 'Sofa', 'Bed', 'Wardrobe', 'Refrigerator', 'Microwave', 'Oven', 'Washing Machine',
     'Television', 'Bookshelf', 'Desk', 'Vacuum Cleaner', 'Toilet', 'Shower', 'Broom'],
    ['Lamp', 'Mirror', 'Coffee Machine', 'Pillow', 'Towel'], true),
  ],
};
