// Practice-bot fact matrix — Pets.
// Words: Dog, Cat, Rabbit, Hamster, Guinea Pig, Goldfish, Parrot, Budgie,
// Turtle, Ferret, Rat, Mouse, Hedgehog, Canary, Cockatiel, Betta Fish,
// Gecko, Snake, Chinchilla, Gerbil.
// q(id, en, nl, yesList, someList, extra) — every word not listed is NO.
// 'sometimes' = genuinely varies (breed/species/setup); the bot commits one
// interpretation per game, and it never eliminates such a word when reading
// the player's answers.
const q = (id, en, nl, yes, some = [], extra = false) => ({ id, en, nl, yes, some, extra });

const MAMMALS = ['Dog', 'Cat', 'Rabbit', 'Hamster', 'Guinea Pig', 'Ferret', 'Rat', 'Mouse', 'Hedgehog', 'Chinchilla', 'Gerbil'];
const BIRDS = ['Parrot', 'Budgie', 'Canary', 'Cockatiel'];
const FISH = ['Goldfish', 'Betta Fish'];
const ALL = [...MAMMALS, ...BIRDS, ...FISH, 'Turtle', 'Gecko', 'Snake'];

export default {
  category: 'Pets',
  questions: [
  q('mammal', 'Is it a mammal?', 'Is het een zoogdier?', MAMMALS),
  q('isdog', 'Is it a dog?', 'Is het een hond?', ['Dog']),
  q('iscat', 'Is it a cat?', 'Is het een kat?', ['Cat']),
  q('small', 'Is it small?', 'Is het klein?',
    ['Hamster', 'Goldfish', 'Budgie', 'Rat', 'Mouse', 'Hedgehog', 'Canary', 'Betta Fish', 'Gecko', 'Gerbil'],
    ['Dog', 'Rabbit', 'Guinea Pig', 'Turtle', 'Ferret', 'Cockatiel', 'Snake', 'Chinchilla', 'Parrot']),
  q('tenkg', 'Is it bigger than 10 kg?', 'Is het zwaarder dan 10 kg?',
    [], ['Dog', 'Snake']),
  q('fur', 'Does it have fur?', 'Heeft het vacht?',
    ['Dog', 'Cat', 'Rabbit', 'Hamster', 'Guinea Pig', 'Ferret', 'Rat', 'Mouse', 'Chinchilla', 'Gerbil'],
    ['Hedgehog']),
  q('feathers', 'Does it have feathers?', 'Heeft het veren?', BIRDS),
  q('scales', 'Does it have scales?', 'Heeft het schubben?',
    ['Goldfish', 'Betta Fish', 'Snake', 'Gecko', 'Turtle']),
  q('fly', 'Can it fly?', 'Kan het vliegen?', BIRDS),
  q('swim', 'Can it swim?', 'Kan het zwemmen?',
    ['Goldfish', 'Betta Fish', 'Turtle'], ['Dog', 'Rat', 'Snake', 'Ferret']),
  q('trained', 'Can it be trained?', 'Kun je het africhten?',
    ['Dog', 'Parrot'], ['Cat', 'Rat', 'Ferret', 'Budgie', 'Cockatiel', 'Rabbit', 'Mouse']),
  q('bark', 'Does it bark?', 'Blaft het?', ['Dog']),
  q('meow', 'Does it meow?', 'Miauwt het?', ['Cat']),
  q('purr', 'Does it purr?', 'Spint het?', ['Cat'], ['Guinea Pig']),
  q('chirp', 'Does it chirp?', 'Tjilpt het?', ['Budgie', 'Canary', 'Cockatiel'], ['Parrot']),
  q('squeak', 'Does it squeak?', 'Piept het?',
    ['Hamster', 'Guinea Pig', 'Rat', 'Mouse', 'Gerbil'], ['Rabbit', 'Chinchilla', 'Ferret']),
  q('noisy', 'Is it noisy?', 'Is het luidruchtig?',
    ['Dog', 'Parrot'], ['Budgie', 'Cockatiel', 'Canary', 'Guinea Pig', 'Ferret']),
  q('quiet', 'Is it quiet?', 'Is het stil?',
    ['Goldfish', 'Betta Fish', 'Turtle', 'Snake', 'Gecko', 'Rabbit', 'Hedgehog'],
    ['Cat', 'Hamster', 'Mouse', 'Gerbil', 'Chinchilla']),
  q('exotic', 'Is it exotic?', 'Is het exotisch?',
    ['Hedgehog', 'Gecko', 'Snake', 'Chinchilla'], ['Ferret', 'Betta Fish', 'Parrot', 'Turtle']),
  q('reptile', 'Is it a reptile?', 'Is het een reptiel?', ['Turtle', 'Gecko', 'Snake']),
  q('rodent', 'Is it a rodent?', 'Is het een knaagdier?',
    ['Hamster', 'Guinea Pig', 'Rat', 'Mouse', 'Chinchilla', 'Gerbil'],
    // Not taxonomically rodents, but casually lumped in constantly.
    ['Rabbit']),
  q('bird', 'Is it a bird?', 'Is het een vogel?', BIRDS),
  q('fish', 'Is it a fish?', 'Is het een vis?', FISH),
  q('israbbit', 'Is it a rabbit?', 'Is het een konijn?', ['Rabbit']),
  q('isguinea', 'Is it a guinea pig?', 'Is het een cavia?', ['Guinea Pig']),
  q('ishamster', 'Is it a hamster?', 'Is het een hamster?', ['Hamster']),
  q('islizard', 'Is it a lizard?', 'Is het een hagedis?', ['Gecko']),
  q('issnake', 'Is it a snake?', 'Is het een slang?', ['Snake']),
  q('isturtle', 'Is it a turtle?', 'Is het een schildpad?', ['Turtle']),
  q('isparrot', 'Is it a parrot?', 'Is het een papegaai?',
    ['Parrot'], ['Budgie', 'Cockatiel']), // technically parrot family
  q('cage', 'Does it live in a cage?', 'Leeft het in een kooi?',
    ['Hamster', 'Parrot', 'Budgie', 'Canary', 'Cockatiel', 'Rat', 'Mouse', 'Gerbil', 'Chinchilla', 'Guinea Pig'],
    ['Rabbit', 'Ferret', 'Hedgehog', 'Gecko', 'Snake', 'Turtle']),
  q('aquarium', 'Does it live in an aquarium?', 'Leeft het in een aquarium?',
    FISH, ['Turtle']),
  q('outdoors', 'Does it live outdoors?', 'Leeft het buiten?',
    [], ['Dog', 'Rabbit', 'Turtle', 'Cat']),
  q('shed', 'Does it shed?', 'Verhaart het?',
    ['Dog', 'Cat', 'Rabbit', 'Ferret', 'Snake', 'Gecko'], // reptiles shed skin
    ['Guinea Pig', 'Hamster', 'Chinchilla', 'Rat', 'Mouse', 'Gerbil']),
  q('meat', 'Does it eat meat?', 'Eet het vlees?',
    ['Cat', 'Dog', 'Ferret', 'Snake'], ['Hedgehog', 'Gecko', 'Turtle', 'Betta Fish', 'Rat', 'Mouse']),
  q('seeds', 'Does it eat seeds?', 'Eet het zaden?',
    ['Parrot', 'Budgie', 'Canary', 'Cockatiel', 'Hamster', 'Gerbil', 'Mouse'],
    ['Rat', 'Guinea Pig', 'Chinchilla', 'Rabbit']),
  q('hay', 'Does it eat hay?', 'Eet het hooi?',
    ['Rabbit', 'Guinea Pig', 'Chinchilla'], ['Gerbil', 'Hamster']),
  q('leash', 'Can it be put on a leash?', 'Kun je het aan de riem doen?',
    ['Dog'], ['Cat', 'Ferret', 'Rabbit']),
  q('nocturnal', 'Is it nocturnal?', 'Is het nachtdier?',
    ['Hamster', 'Hedgehog', 'Gecko', 'Chinchilla'], ['Rat', 'Mouse', 'Gerbil', 'Ferret', 'Cat', 'Snake']),
  q('hibernate', 'Does it hibernate?', 'Houdt het een winterslaap?',
    [], ['Turtle', 'Hedgehog', 'Hamster']),
  q('expensive', 'Is it expensive to keep?', 'Is het duur om te houden?',
    ['Parrot'], ['Dog', 'Cat', 'Chinchilla', 'Snake', 'Ferret', 'Turtle', 'Gecko']),
  q('longlife', 'Does it live more than 10 years?', 'Wordt het ouder dan 10 jaar?',
    ['Cat', 'Parrot', 'Turtle', 'Cockatiel', 'Snake', 'Chinchilla', 'Gecko'],
    ['Dog', 'Goldfish', 'Canary', 'Budgie', 'Rabbit']),
  q('children', 'Is it good with children?', 'Is het goed met kinderen?',
    ['Dog', 'Guinea Pig'], ['Cat', 'Rabbit', 'Hamster', 'Goldfish', 'Budgie', 'Gerbil', 'Rat']),
  q('territorial', 'Is it territorial?', 'Is het territoriaal?',
    ['Betta Fish'], ['Cat', 'Dog', 'Hamster', 'Gecko', 'Snake', 'Ferret', 'Rabbit']),
  q('longtail', 'Does it have a long tail?', 'Heeft het een lange staart?',
    ['Cat', 'Rat', 'Mouse', 'Gerbil'],
    ['Dog', 'Ferret', 'Gecko', 'Chinchilla', 'Snake', 'Parrot', 'Cockatiel']),
  q('whiskers', 'Does it have whiskers?', 'Heeft het snorharen?',
    ['Cat', 'Dog', 'Rabbit', 'Hamster', 'Guinea Pig', 'Rat', 'Mouse', 'Ferret', 'Chinchilla', 'Gerbil'],
    ['Hedgehog']),
  q('claws', 'Does it have claws?', 'Heeft het klauwen?',
    ['Dog', 'Cat', 'Rabbit', 'Hamster', 'Guinea Pig', 'Ferret', 'Rat', 'Mouse', 'Hedgehog', 'Chinchilla',
     'Gerbil', 'Parrot', 'Budgie', 'Canary', 'Cockatiel', 'Gecko', 'Turtle']),
  q('popular', 'Is it a popular pet?', 'Is het een populair huisdier?',
    ['Dog', 'Cat', 'Rabbit', 'Hamster', 'Goldfish', 'Guinea Pig', 'Budgie'],
    ['Parrot', 'Canary', 'Cockatiel', 'Rat', 'Mouse', 'Turtle', 'Betta Fish', 'Gerbil']),
  q('purrchirp', 'Does it purr or chirp?', 'Spint of tjilpt het?',
    ['Cat', 'Budgie', 'Canary', 'Cockatiel'], ['Parrot', 'Guinea Pig']),
  q('tricks', 'Can it learn tricks?', 'Kan het kunstjes leren?',
    ['Dog', 'Parrot', 'Rat'], ['Cat', 'Ferret', 'Budgie', 'Cockatiel', 'Mouse', 'Rabbit', 'Guinea Pig']),

  // ── Answer-only extras: common free-text phrasings, honest by lookup ──────
  q('x_alive', 'Is it alive?', 'Leeft het?', ALL, [], true),
  q('x_animal', 'Is it an animal?', 'Is het een dier?', ALL, [], true),
  q('x_person', 'Is it a person?', 'Is het een persoon?', [], [], true),
  q('x_place', 'Is it a place?', 'Is het een plek?', [], [], true),
  q('x_thing', 'Is it a thing?', 'Is het een ding?', [], ALL, true),
  q('x_manmade', 'Is it man-made?', 'Is het door mensen gemaakt?', [], [], true),
  q('x_natural', 'Is it natural?', 'Is het natuurlijk?', ALL, [], true),
  q('x_eat', 'Can you eat it?', 'Kun je het eten?', [], [], true),
  q('x_cute', 'Is it cute?', 'Is het schattig?', [], ALL, true),
  q('x_dangerous', 'Is it dangerous?', 'Is het gevaarlijk?', [], ['Snake'], true),
  q('x_legs', 'Does it have legs?', 'Heeft het poten?',
    [...MAMMALS, ...BIRDS, 'Turtle', 'Gecko'], [], true),
  q('x_fourlegs', 'Does it have four legs?', 'Heeft het vier poten?',
    [...MAMMALS, 'Turtle', 'Gecko'], [], true),
  q('x_wings', 'Does it have wings?', 'Heeft het vleugels?', BIRDS, [], true),
  q('x_tail', 'Does it have a tail?', 'Heeft het een staart?',
    ['Dog', 'Cat', 'Rat', 'Mouse', 'Gerbil', 'Gecko', 'Ferret', 'Chinchilla', 'Goldfish', 'Betta Fish',
     'Parrot', 'Budgie', 'Canary', 'Cockatiel'],
    ['Rabbit', 'Hamster', 'Hedgehog', 'Turtle', 'Snake'], true),
  q('x_teeth', 'Does it have teeth?', 'Heeft het tanden?',
    MAMMALS, ['Gecko', 'Snake', 'Goldfish', 'Betta Fish'], true),
  q('x_ears', 'Does it have visible ears?', 'Heeft het zichtbare oren?',
    ['Dog', 'Cat', 'Rabbit', 'Hamster', 'Guinea Pig', 'Ferret', 'Rat', 'Mouse', 'Chinchilla', 'Gerbil'],
    ['Hedgehog'], true),
  q('x_sing', 'Can it sing?', 'Kan het zingen?',
    ['Canary'], ['Budgie', 'Cockatiel', 'Parrot'], true),
  q('x_talk', 'Can it talk?', 'Kan het praten?',
    ['Parrot'], ['Budgie', 'Cockatiel'], true),
  q('x_walk', 'Can it walk?', 'Kan het lopen?',
    [...MAMMALS, ...BIRDS, 'Turtle', 'Gecko'], [], true),
  q('x_biggercat', 'Is it bigger than a cat?', 'Is het groter dan een kat?',
    [], ['Dog', 'Snake'], true),
  q('x_common', 'Is it common?', 'Is het gewoon?',
    ['Dog', 'Cat', 'Goldfish', 'Rabbit', 'Hamster', 'Budgie', 'Guinea Pig'],
    ['Parrot', 'Canary', 'Cockatiel', 'Rat', 'Mouse', 'Turtle', 'Betta Fish', 'Gerbil', 'Ferret'], true),
  q('x_famous', 'Is it famous?', 'Is het beroemd?', [], [], true),
  q('x_kids', 'Is it something kids know about?', 'Kennen kinderen het?', ALL, [], true),
  q('x_colourful', 'Is it colourful?', 'Is het kleurrijk?',
    ['Parrot', 'Betta Fish'], ['Budgie', 'Canary', 'Goldfish', 'Cockatiel'], true),
  q('x_green', 'Is it green?', 'Is het groen?',
    [], ['Turtle', 'Gecko', 'Budgie', 'Parrot', 'Snake'], true),
  q('x_soft', 'Is it soft?', 'Is het zacht?',
    ['Cat', 'Rabbit', 'Chinchilla', 'Dog', 'Hamster', 'Guinea Pig', 'Gerbil'],
    ['Ferret', 'Rat', 'Mouse'], true),
  ],
};
